### PR TITLE
call python explicitly and use command echo to stdout (IDFGH-3333)

### PR DESCRIPTION
**Pull request by callalilychen**
a possible solution to solve the issue #5313

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@callalilychen Thanks for your contribution.

**Comment by renzbagaporo** [comment]
Hi @callalilychen, this seems to have lots of changes?

**Comment by renzbagaporo** [comment]
Hi @callalilychen, this seems to have lots of unintended changes?

**Comment by renzbagaporo** [comment]
Hi @callalilychen, this PR seems unintentionally includes other changes?

**Comment by renzbagaporo** [comment]
Hi @callalilychen, unfortunately we can't use `COMMAND_ECHO` as it seems to be present on CMake 3.15 onwards  only. We currently guarantee support for version as low as CMake 3.5.

**Pull request closed without merging**
