### PR TITLE
Bugfixes for BLE & HID (IDFGH-5832)

### PR DESCRIPTION
**Pull request by finger563**
* Feature: Allow hid event handler registration to include event handler arguments like other event handler systems.
* Bugfix to hid_event_data to actually fill out the data field from the report
* Bugfix to post the correct amount of data when posting the event data
* Bugfix to properly call HID callback with CLOSE_EVT properly when HID device is closed.

Edit: related to issues
* https://github.com/espressif/esp-idf/issues/7211
* https://github.com/espressif/esp-idf/issues/7139

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by Wth-Esp** [comment]
Hi， @finger563 

I'm glad to see this PR, thank you very much.

But could you please wait for several days? We have an internal update for the hid component which has been reviewed and the update is about to be merged. So, could you please rebase on that commit (I will notify you in this PR...) in the near future and see whether the fix you come up with is still effective?

Thanks for your contributions.

**Comment by Wth-Esp** [comment]
Hi, @finger563 

The commit `2078dfe2932496101376cc7a68a224048b2afd56` already merged on the master branch, please wait for sync on Github and rebase your PR.

Thanks

**Comment by Wth-Esp** [comment]
Hi, @finger563 

Thanks for your contribution again, changes synced with `2078dfe`.

Please change to the master branch and see whether the issues are still there. If yes, please raise a PR for the master branch first.

Thanks

**Comment by finger563** [comment]
Thanks @Wth-Esp - we've tested and will close this PR to open a new PR with the remaining changes :)

**Pull request closed without merging**
