### PR TITLE
Fix typos in README (IDFGH-2417)

### PR DESCRIPTION
**Pull request by NathanJPhillips**
Fix a broken link as well as updating the text.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@NathanJPhillips Thanks for the contribution.

**Comment by NathanJPhillips** [comment]
No problem - is this going to be merged? Just asking because if contributions don't get merged then I probably shouldn't submit any more substantial contributions.

**Comment by krzychb** [comment]
Hi @NathanJPhillips, LGTM! 
I will add your PR to the merge queue. 
Thanks :+1:

**Comment by krzychb** [comment]
Merged in 23e6ee9d013df307de3f1161416ca61bef4c669f

**Pull request closed without merging**
