### PR TITLE
Modbus master example: Fix a misplaced assert in the master init function (IDFGH-6988)

### PR DESCRIPTION
**Pull request by nouwaarom**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by alisitsyn** [comment]
Hi @nouwaarom,

Thank you for your contribution, the issue has been confirmed. This misplaced error check macro has to be fixed.

**Comment by alisitsyn** [comment]
@nouwaarom,

The fix starts to go through the internal workflow process. I will notify you once it is ready for merge.

**Comment by alisitsyn** [comment]
@nouwaarom,

The fix was merged with commit e653ce82b2ce0951638a4b88fc6f81b4db0ec166.
The backports are pending.

**Pull request closed without merging**
