### PR TITLE
[py] SSL_DS Fix script for Windows (IDFGH-7353)

### PR DESCRIPTION
**Pull request by KonssnoK**
Let the script run on a windows machine

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by AdityaHPatwardhan** [comment]
Hi @KonssnoK Can you please try this [script](https://github.com/espressif/esp_secure_cert_mgr/blob/main/tools/configure_esp_secure_cert.py) i.e. `configure_esp_secure_cert.py`. The script performs similar operations but with a different NVS namespace.
The current script `configure_ds.py` shall be removed soon and it will be replaced with `configure_esp_secure_cert.py` in the `ssl_ds` example.

**Comment by KonssnoK** [comment]
ah, i see you made the same changes i made for our devices, by putting ca and client CRT in the same partition as the ds_data.
I'll try the script when possible

**Comment by AdityaHPatwardhan** [comment]
@KonssnoK The configuration tool for Digital Signature peripheral has now been pushed to PyPi as a python package.
You may view the package at https://pypi.org/project/esp-secure-cert-tool/

you may use following command to download the packege:
`pip install esp-secure-cert-tool`

Please find the additional options in the help menu of the script on this package is installed.
`configure_esp_secure_cert.py -h`

If it solves your query, you may close the PR. Thanks

**Comment by mahavirj** [comment]
Closing as this script has now been moved in an independent package https://pypi.org/project/esp-secure-cert-tool/. Also this package should fix problem on Windows host too.

**Pull request closed without merging**
