### PR TITLE
Fix instance names for event handler unregistering in WiFi station example (IDFGH-3039)

### PR DESCRIPTION
**Pull request by jarijokinen**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@jarijokinen Thanks for your contribution. We will look into.

**Comment by Alvin1Zhang** [comment]
@jarijokinen Thanks for your contribution, we have put this into our internal reviewing, thanks.

**Comment by AxelLin** [comment]
This should be closed since it's merged by 266b0c38891db60e5188bffcac9d97950008fe87.

**Comment by Alvin1Zhang** [comment]
@jarijokinen Thanks for the contribution and thanks @AxelLin  for the notes, changes merged with https://github.com/espressif/esp-idf/commit/266b0c38891db60e5188bffcac9d97950008fe87

**Pull request closed without merging**
