### PR TITLE
rtc_tempsensor: fix log level (IDFGH-6529)

### PR DESCRIPTION
**Pull request by dreamcmi**
ESP32C3 rtc_tempsensor.c log level issue, printf has been changed to esp-log

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by suda-morris** [comment]
sha=64120fa7f459aef28a3bc843ff8aee1491405268

**Comment by mythbuster5** [comment]
@dreamcmi This issue has been fixed. The new temperature sensor api has been immigrated to. https://github.com/espressif/esp-idf/blob/master/components/driver/temperature_sensor.c. But the old one is still avaliable https://github.com/espressif/esp-idf/blob/master/components/driver/rtc_temperature_legacy.c. Please take a look.

And this one will be closed.

**Comment by dreamcmi** [comment]
> @dreamcmi This issue has been fixed. The new temperature sensor api has been immigrated to. https://github.com/espressif/esp-idf/blob/master/components/driver/temperature_sensor.c. But the old one is still avaliable https://github.com/espressif/esp-idf/blob/master/components/driver/rtc_temperature_legacy.c. Please take a look.
> 
> And this one will be closed.

Thanks, I also hope that this log printing problem can be fixed in the release/v4.3 branch, because if it is not modified, some unnecessary data will be automatically printed when the program is running.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again.

**Pull request closed without merging**
