### PR TITLE
esp_crt_bundle: remove EC-ACC certificate (IDFGH-5944)

### LINKED ISSUE #7631: Can't load some certificates with cryptography v35.0.0
## Problem Description

The latest cryptography python module doesn't allow to [parse X.509 certificates with negative serial numbers]( https://github.com/pyca/cryptography/blob/35.0.0/CHANGELOG.rst). This new behavior affects the [EC-ACC certificate](https://github.com/espressif/esp-idf/blob/v4.3/components/mbedtls/esp_crt_bundle/cacrt_all.pem#L1648-L1676).

```bash
$ openssl x509 -in ec-acc.pem -text                                                                                               
Certificate:                                                    
    Data:                                                       
        Version: 3 (0x2)                                        
        Serial Number:                                          
             (Negative)11:d4:c2:14:2b:de:21:eb:57:9d:53:fb:0c:22:3b:ff
        Signature Algorithm: sha1WithRSAEncryption
```

### Expected Behavior

```bash
$ python components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input components/mbedtls/esp_crt_bundle/cacrt_all.pem -q
```

### Actual Behavior

```bash
$ python components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input components/mbedtls/esp_crt_bundle/cacrt_all.pem -q
gen_crt_bundle.py: Invalid certificate in components/mbedtls/esp_crt_bundle/cacrt_all.pem
Invalid certificate
```

### Steps to reproduce

```bash
$ virtualenv .venv
$ source .venv/bin/activate
$ IDF_PATH=$(pwd) pip install -r requirements.txt
$ python components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input components/mbedtls/esp_crt_bundle/cacrt_all.pem -q
```

### PR DESCRIPTION
**Pull request by electrocucaracha**
Removing the EC-ACC certificate given it has Negative serial value invalid for [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.2). 

Fix #7631

### CODE REVIEW

**Review by RadicalDev — COMMENTED** [review]
Thanks for the quick fix!

**Review by mahavirj — APPROVED** [review]

**Comment by asurti9** [comment]
Thanks for the quick fix!
Is this fix permanent? Or we will be having a permanent fix in future?

**Comment by igrr** [comment]
@asurti9 There will be a follow-up update of the certificate bundle, please see https://github.com/espressif/esp-idf/issues/7631#issuecomment-934212224.

**Comment by niwantha33** [comment]
it works. thanks

**Pull request merged**
