### PR TITLE
Make sure ESP_PLATFORM is defined when processing CMake files. (IDFGH-1721)

### PR DESCRIPTION
**Pull request by PerMalmberg**
So this is a PR I have a strong feeling I've submitted once before, but the functionality seems to have been lost in IDF master.

Given the following project layout:

Top CMakeList.txt:
```
cmake_minimum_required(VERSION 3.10)

set(CMAKE_CXX_STANDARD 17)

if(${ESP_PLATFORM})
    include($ENV{IDF_PATH}/tools/cmake/project.cmake)
    set(FOO 1)

    # Include Smooth as a component
    set(EXTRA_COMPONENT_DIRS
             externals/smooth/smooth_component)
    project(g3)
else()
    add_subdirectory(main)
    add_subdirectory(externals/smooth/lib)
endif()
```

main/CMakeList.txt:
```

cmake_minimum_required(VERSION 3.10)

include(${CMAKE_CURRENT_LIST_DIR}/files.cmake)

if(${ESP_PLATFORM})
    idf_component_register(SRCS ${SOURCES}
            INCLUDE_DIRS
            ${CMAKE_CURRENT_LIST_DIR}
            $ENV{IDF_PATH}/components
            REQUIRES
            smooth_component
            )
else()
    project(g3.elf)
    include(files.cmake)
    add_executable(${PROJECT_NAME} ${SOURCES})
    target_link_libraries(${PROJECT_NAME} smooth)
    target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_LIST_DIR})
endif()
```
When running  `cd build && cmake .. -G "Ninja" -DESP_PLATFORM=1 -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake`, `ESP_PLATFORM` is defined in the top CMakeList.txt however, it is not when processing `main/CMakeList.txt` resulting in the wrong script path being processed.

Would be awesome if this can be included in v4.

### CODE REVIEW

**Comment by PerMalmberg** [comment]
@renzbagaporo Shameless ping since the JIRA sync failed - can you do something about it so this PR can be marked with "all checks passed"?

**Comment by renzbagaporo** [comment]
>So this is a PR I have a strong feeling I've submitted once before

You're definitely not wrong! Thanks for catching this regression @PerMalmberg.

Regarding the sync issue, I don't think you have to mind this. Somehow this still got synced to our internal JIRA anyway.

**Comment by PerMalmberg** [comment]
So I see this has been merged into IDF-master six days ago, is there a reason the PR is kept open?

**Comment by projectgus** [comment]
@PerMalmberg No reason, thanks for contributing the patch. Sorry for the hassle about the regression and the JIRA sync problem, something has changed on the GitHub Actions side now they're out of beta and we need to debug it.

**Comment by PerMalmberg** [comment]
Sorry to bring this one up again, but it seems this didn't make it into v.4.0-beta-1. Will master be merged again to v.4.0 before final release or will I have to continue working off master to get this fix?

**Pull request closed without merging**
