### PR TITLE
Porting recvmsg() from upstream LwIP

### PR DESCRIPTION
**Pull request by SStorm**
Hi guys, as discussed in issue #1460, this is updating LwIP with the latest changes to support recvmsg(). There are no automatic unit tests for this, so I have only done some manual regression testing and it did not seem to break anything. Also the recvmsg() functionality is working as intended. Just to be clear this is not my code, but rather directly taken from upstream LwIP, so all the licenses apply. Unfortunately the esp-idf implementation is customised extensively, so a bona-fide patch did not work and I had to copy specific parts manually. 

There are some dodgy bits that I did not know what to do with (i.e. coap). These are generally annotated with a FIXME.

Looking for feedback at the moment more than an actual merge. Happy to donate time to this, i.e. for writing up some unit tests.

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks for sending this, @SStorm . I'm not sure if we can merge this directly as-is, because upgrading parts of LWIP is quite a painstaking process to avoid regressions. Can you comment at all about the testing you've done with this?

Regardless of whether we can merge this now, I'm sure @TimXia and @liuzfesp will take a look and see if they can use these patches as a basis for part of the LWIP upgrading efforts.

**Comment by SStorm** [comment]
@projectgus I ran all of the automated tests on esp-idf, plus manually tested both TCP and UDP connectivity, namely:
1. Creating a socket
2. Binding a socket
3. select()
4. Receiving from a socket (recvmsg, recv)
5. Sending to a socket 
6. Closing sockets

However, there are no automatic regression tests of LwIP so it's quite hard to be certain in the end. As I've said, I don't think this is mergeable as is, but would appreciate some feedback from someone knowledgeable on the matter and happy to donate some time to port this across properly.

**Comment by daniol** [comment]
Can someone fix this?
It's a nightmare to make it work in esp-idf, as the include folders have changed.

**Comment by projectgus** [comment]
@daniol A lot of things have changed since this PR was opened. LWIP is now a submodule in ESP-IDF, currently based on LWIP v2.0.3. The code is much closer to upstream LWIP than before. Compared to when this PR was opened there is support for `recvmsg()` now, but not for `IP_PKTINFO`.

I reopened the linked issue #1460 with some details about support for `IP_PKTINFO`. If you want to hack support for `IP_PKTINFO` into ESP-LWIP now to make an unsupported version, the best thing to do is probably to apply the upstream commit onto the ESP-LWIP repo (this doesn't currently `git cherry-pick` cleanly, I tried, but probably less changes than compared to this PR branch).

Please follow the linked issue for further updates once available.

**Pull request closed without merging**
