### PR TITLE
fix(usb_serial_jtag): Incomplete flushing of HW FIFO causes the truncated output from USB Serial/JTAG on esp32-s3 (IDFGH-11121)

### PR DESCRIPTION
**Pull request by andylinpersonal**
# Environment

* OS: Linux x64
* IDE: None (idf.py) / VSCode
* Chip: ESP32-S3R8(V) rev 0.1
* Board: ESP32-S3-DevkitC-1-N32R8V / custom board with ESP32-S3-WROOM-1-N16R8
* Console: cat /dev/ttyPORT / idf.py monitor / minicom / GNU screen
* Tested IDF ver: release/v5.1 and master

# Problem

* The console output via USB Serial/JTAG on esp32s3 may be unreliable under multitasking environment.
* If someone unplugged and reconnected the USB cable linked to USB Serial/JTAG under high output traffic, the bug could also be triggered after a short period of time.

# Cause

* Sometimes the hardware FIFO of USB Serial/JTAG cannot be flushed completely, but the return value from the underlying LL layer is ignored. Thus the displayed texts are truncated.

# Fix / Workarounds

* Return the unfinished part of the retrieved buffer back to the Ringbuffer
* Add a stash buffer to the driver object and copy the unfinished bytes into it. See https://github.com/espressif/esp-idf/pull/11344.

# Output

* Broken and truncated output from b15d5ca6cafa23c1132dbaa46d11965bced4d687

```
I (21216) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21216) USB Serial/JTAG: 1 print lots of message from 4 I (21216) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21246) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21246) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21246) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (21246) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21266) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21266) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21266) USB Serial/JTAG: 1 print lots of message from 4 0m
I (21266) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21276) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21276) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21276) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (21276) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (21296) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21306) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21306) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21306) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (21306) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21336) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21336) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21336) USB Serial/JTAG: 1 print lots of message from 4 I (21336) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21356) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21356) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21356) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (21356) USB Serial/JTAG: 3 print lots of message from 4 tasI (21366) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21366) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21366) USB Serial/JTAG: 1 print lots of message fI (21366) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21386) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (21386) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (21386) USB Serial/JTAG: 1 print lots of message fI (21386) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (21406) USB Serial/JTAG: 0 print lots of message from 4 tasks
```

* Fixed output from the USB Serial/JTAG after applying 9f3d8edb83f59a49fbdf0ba5fbb94ceecff24d07

```
I (11915) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11915) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11915) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11915) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11915) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11925) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11935) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (11935) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (11935) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11935) USB Serial/JTAG: 3 print lots of message from 4 tasks
I (11945) USB Serial/JTAG: 0 print lots of message from 4 tasks
I (11945) USB Serial/JTAG: 2 print lots of message from 4 tasks
I (11945) USB Serial/JTAG: 1 print lots of message from 4 tasks
I (11945) USB Serial/JTAG: 3 print lots of message from 4 tasks
```

# Note

b15d5ca is the basic test case and it is also acted as a MWE for demonstrating the effectiveness of the fix 9f3d8ed.

# Reproduce steps

See https://github.com/espressif/esp-idf/pull/12291#issuecomment-1731529497

# Related Issue

https://github.com/espressif/esp-idf/pull/11344/files [fixed here but not merged yet]

### CODE REVIEW

**Comment by igrr** [comment]
@andylinpersonal The fix was recently merged into master branch with https://github.com/espressif/esp-idf/commit/e2eb773c3052ab302d4d9f700f4909870667197e, can you try cherry-picking this commit to your release branch and see if that helps? We will backport the fix to release branches soon.

**Comment by andylinpersonal** [comment]
@igrr 

Sorry, it seems like this fix (e2eb773) is not the same issue as my fix.
I've tested this patch on release/v5.1 and master but unfortunately, it does not fix the issue.

The root cause of this issue comes from the hardware fifo of s3's usb serial/jtag not flushed completely.

You can apply the attached patch to my [b15d5ca](https://github.com/espressif/esp-idf/pull/12291/commits/b15d5ca6cafa23c1132dbaa46d11965bced4d687)

Following output is the result:

image

[0001-MWE-failed-to-flush-the-hardware-fifo.patch.txt](https://github.com/espressif/esp-idf/files/12701851/0001-MWE-failed-to-flush-the-hardware-fifo.patch.txt)

**Comment by andylinpersonal** [comment]
Hi @igrr,

This bug has indeed been fixed in https://github.com/espressif/esp-idf/pull/11344 by @chipweinberger.
But https://github.com/espressif/esp-idf/pull/11344 has been closed by https://github.com/espressif/esp-idf/commit/e2eb773c3052ab302d4d9f700f4909870667197e without merging the fix. 
Is it still WIP?

Thanks.

**Comment by chipweinberger** [comment]
looks like [11344](https://github.com/espressif/esp-idf/pull/11344) was merged to master https://github.com/espressif/esp-idf/commit/923fcc25b65668e03484557624492e18676fe80f

**Comment by andylinpersonal** [comment]
Close due to solved in the commit https://github.com/espressif/esp-idf/commit/923fcc25b65668e03484557624492e18676fe80f. Looking forward to porting back to other release branches 😄

**Comment by ginkgm** [comment]
Target Branch | Merged | Supported | Last N.A.
-- | -- | -- | --
release/v5.1 | ea5e749 | null | v5.1.1
master | 923fcc2 | v5.2 | null

Target Branch	Merged	Supported	Last N.A.
release/v5.1	[ea5e749](https://github.com/espressif/esp-idf/commit/ea5e7490f3a29331b04a8321b5f7a76d1689c5ea)	null	v5.1.1
master	[923fcc2](https://github.com/espressif/esp-idf/commit/923fcc25b65668e03484557624492e18676fe80f)	v5.2	null

**Pull request closed without merging**
