### PR TITLE
Changed ParseException message argument (IDFGH-3360)

### PR DESCRIPTION
**Pull request by the-cat-that-codes**
The 'message' attribute seems to be not usable since python 3.0 (see PEP #352 : https://www.python.org/dev/peps/pep-0352/#exception-hierarchy-changes)
but 'msg' is a valid attribute for pyparsing.ParseException.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@the-cat-that-codes Thanks for contribution.

**Comment by renzbagaporo** [comment]
Hi @the-cat-that-codes, thanks for the PR! The changes here look good to me. Although the commit eaf45773f37564440379caf144f86b2c50e0bdbd seem to have the commit description cut off? 

Thanks for the heads up about PEP #352. I will probably end up fixing some more instances of `.message` use on top of your changes here!

**Comment by the-cat-that-codes** [comment]
Hello @renzbagaporo,

I am sorry for the mistakes, it is my first collaboration on a public base. I will take more care in the future.
The commit eaf4577 was not planned to be in this PR. Initially, I wanted to propose another PR for this "issue" which is not really an issue at all. 
For the story, I have found the .message issue because my development system is in french and so there are some accented characters in some file paths. Due to these accented characters, the ParseException was raised but also an other one, the attribute error. I found that the attribute error has to be corrected. That was the goal of my first PR.
For the second (the commit eaf4577), I am not sure that supporting accented characters in path of libraries is required because it seems that it is not very common to use accented characters in directories and file paths (although in my opinion, in 2020, using any characters should not be a problem anymore :-). The message of this commit is : 

**_Allow accented characters in full filepaths of archives used in the generation._**

**Comment by renzbagaporo** [comment]
@the-cat-that-codes Cleaning up this PR to only include the `.message()` fix and opening another PR for the accented characters fix is OK with me.

I see no harm in the accented characters change, and frankly, it's something that I haven't considered. So thanks for bringing this into our attention!

**Comment by the-cat-that-codes** [comment]
@renzbagaporo Ok I will do the changes but  have you an advice to do it well (and in order to not introduced other errors in this PR). Maybe you have an hyperlink to follow for having a procedure to make the clean up of this PR safely ?

**Comment by the-cat-that-codes** [comment]
Hi @renzbagaporo,

I have cleaned up the PR but I think there is an other problem since I am not the author of the commit c8f3ca7.
What I have done is :
- git pull in my fork
- rebase to drop the bad commits (the one with wrong email)
- and reset --soft the commit about the accented character (in order to keep the changes for an other PR)
- finally push on my own fork
Any ideas on what happened ?

**Comment by renzbagaporo** [comment]
I'm not sure either. I can drop `c8f3ca7` in our internal submission if that's ok with you @the-cat-that-codes.

**Comment by the-cat-that-codes** [comment]
@renzbagaporo Oh yes, sorry the late answer ... of course, you can drop the c8f3ca7 if you want.

**Pull request closed without merging**
