### PR TITLE
Patched sprintf usage (IDFGH-5175)

### PR DESCRIPTION
**Pull request by PBearson**

### CODE REVIEW

**Comment by AxelLin** [comment]
Why not using strcpy instead?

**Comment by PBearson** [comment]
> Why not using strcpy instead?

Good point, I guess strcpy is better in this case. I updated to strncpy and used the defined WPS macros for the bounds lengths. For example:

` strncpy(dev->manufacturer, s_factory_info->manufacturer, WPS_MAX_MANUFACTURER_LEN);`

**Comment by Alvin1Zhang** [comment]
@PBearson Thanks for your contribution.

**Comment by kapilkedawat** [comment]
Hi @PBearson , we use snprintf now which checks for bound limitation, therefore this change is not needed anymore.

**Comment by Alvin1Zhang** [comment]
Thanks for contribution again.

**Pull request closed without merging**
