### PR TITLE
Update i2c.c to consider two I2C buses for clear bus counter (IDFGH-5398)

### PR DESCRIPTION
**Pull request by iltis42**
Fix issue with single bus clear counter but two I2C buses (I2C0, I2C1). The previously implemented single (static) counter would impact the second bus either if one bus has counter expiry.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by iltis42** [comment]
Any news about this ?
The single counter is obviously an epic bug, any dual I2C bus board will run into that issue.

**Comment by o-marshmallow** [comment]
sha=2cb7ae03072ad7f3f580fee577e626f3c3ef08c8

**Comment by o-marshmallow** [comment]
Hi @iltis42 ,
I am going to handle it to get it merged in master.

**Comment by Alvin1Zhang** [comment]
Changes merged with https://github.com/espressif/esp-idf/commit/0257eba526756d2f03f8392d6375dd01a3e71c83, thanks for your contribution again.

**Pull request closed without merging**
