### PR TITLE
Update README.md of OTA Example (IDFGH-5285)

### PR DESCRIPTION
**Pull request by a2800276**
Made some grammatical corrections and improved reading flow.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, and sorry for late reply, we have put the changes into our internal review queue, and the PR will be updated once the changes are available on GitHub. Thanks.

**Comment by a2800276** [comment]
No worries, these aren't pressing changes, just nudges to make the docs more easily readable :) Thanks for keeping me in the loop!

**Comment by igrr** [comment]
Thank you for the contribution! The PR has been cherry-picked as https://github.com/espressif/esp-idf/commit/bdea007a379b272c37cf14c8cde493a26491f18b.

**Pull request closed without merging**
