### PR TITLE
fix(i2c_master): Do not busy wait on sync transactions (IDFGH-12280)

### PR DESCRIPTION
**Pull request by KJ7LNW**
This commit introduces a private member `i2c_master_bus_t::in_progress_semphr` which allows `i2c_master_transmit` and related functions to give up their timeslice so other tasks can proceed.

Without this commit, one must delay at least one tick via `vTaskDelay(1)` to prevent trigging the idle watchdog, thus limiting the maximum I2C transaction rate to about the speed of `CONFIG_FREERTOS_HZ`.

With this commit, over 6600 samples/sec are possible and the tick delay is unnecessary.

CPU usage below was measured using `vTaskGetRunTimeStats()`.  The FreeRTOS %CPU numbers seem to increase over time and level out after a time, so CPU usage was sampled after 5 seconds across each test for consistency across measurements. Measurements were taken with `CONFIG_FREERTOS_HZ` set to 100Hz and 1000Hz:

Before:
-  100Hz: samples/sec=  99 with  1% CPU ( 99.0 samples/%cpu)
- 1000Hz: samples/sec= 995 with 10% CPU ( 99.5 samples/%cpu)

After:
-  100Hz: samples/sec=6637 with 23% CPU (288.6 samples/%cpu)
- 1000Hz: samples/sec=6610 with 24% CPU (275.4 samples/%cpu)

Closes: https://github.com/espressif/esp-idf/issues/13137

### CODE REVIEW

**Comment by KJ7LNW** [comment]
We used this simple project to test the PR change:

- https://github.com/KJ7LNW/esp32-i2c-test/tree/master

Be sure to comment the `vTaskDelay(1)` line here, or the samples/sec will be limited to your `CONFIG_FREERTOS_HZ` rate:

https://github.com/KJ7LNW/esp32-i2c-test/blob/master/main/i2c-test.c#L152

**Comment by KJ7LNW** [comment]
The force-push is a minor change: It simply sets `HPTaskAwoken` to true when `i2c_master->trans_done == true` to wake the caller.  

This reduces latency and increases the i2c sample rates to 6612 (1000Hz) and 6648 (100Hz).

**Comment by mythbuster5** [comment]
Thanks a lot for this contribution. I am going to create an event queue instead of semaphore. Which can be used to store more information.

**Comment by jrahlf** [comment]
@nebkat that does not make sense to me.
Interrupts do not run on any task, they interrupt tasks. If the I2C ISR yields at the end, the scheduler runs at the end of the ISR, instead of at the end of the current time slice. Of course FreeRTOS respects the priorities of the tasks here.

**Comment by nebkat** [comment]
@jrahlf You're right my explanation was inaccurate, it would jump back to the higher priority task anyway. But we would have run the scheduler unnecessarily, so still better this way.

I have also learned `pxHigherPriorityTaskWoken` will only ever be set to `true` (it is or-ing), so there is no need for the `HPTaskAwokenInProgress` here

**Comment by KJ7LNW** [comment]
Out of curiosity I wondered how task notifications perform, which FreeRTOS [claims to be up to 45% faster](https://www.freertos.org/2020/09/decrease-ram-footprint-and-accelerate-execution-with-freertos-notifications.html) than semaphores:
 
Notifications:
-   100Hz: samples/sec= 6654 with 18% CPU (efficiency: 369.7  samples/%cpu)
- 1000Hz: samples/sec= 6636 with 18% CPU (efficiency: 368.7 samples/%cpu)

Semaphores: (copied from above)
-  100Hz: samples/sec=6637 with 23% CPU (efficiency: 288.6 samples/%cpu)
- 1000Hz: samples/sec=6610 with 24% CPU (efficiency: 275.4 samples/%cpu)

As you can see, notifications are faster and CPU efficiency is _much_ higher with the task notification implementation.

I've pushed a commit converting to notifications on this PR so you can see the difference.

**Pull request closed without merging**
