### PR TITLE
Fix DCE deference crash in pppos example (IDFGH-5730)

### PR DESCRIPTION
**Pull request by mgigante**
Fix DCE deference crash in pppos example

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by david-cermak — APPROVED** [review]
Thanks for the fix!
could you please click through the `CLAassistant` so we can accept this PR?

**Comment by Alvin1Zhang** [comment]
@mgigante Thanks for your contribution. Could you please help click through the CLAassistant so we can accept this PR?

**Comment by Alvin1Zhang** [comment]
@mgigante Thanks for your contribution. Could you please help click through the CLAassistant so we can accept this PR? Thanks.

**Comment by mgigante** [comment]
@Alvin1Zhang sorry for the delay, for some reason I didn't receive notifications in my email box.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again, changes merged with https://github.com/espressif/esp-idf/commit/b40b22c13639fefd43b7a9de6b196b1223831f1e.

**Pull request closed without merging**
