### PR TITLE
Same sense of meaning SW_STRAP

### PR DESCRIPTION
**Pull request by ESP32DE**

### CODE REVIEW

**Comment by negativekelvin** [comment]
Separate commits and separate pull requests!?

**Comment by ESP32DE** [comment]
;-) sry
was my mistake.
want make one pull request with 2 edit files.
but could not add the second edit to the other file to the one pull request

Still has to practice pull request

best wishes
rudi ;-)

**Comment by projectgus** [comment]
Thanks for this, Rudi. I've squashed this commit with the one from #366 and added them to our internal review & merge queue.

**Comment by projectgus** [comment]
Cherry-picked in  f4c4787, thanks again!

**Pull request closed without merging**
