### PR TITLE
Zero-fill netif on alloc

### PR DESCRIPTION
**Pull request by rojer**
Fixes espressif/esp-idf#133

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks @rojer. We have this in our internal review/merge queue, it should be in master soon.

**Comment by rojer** [comment]
ok, i'll close this then.

**Comment by projectgus** [comment]
Sorry, I meant we have your branch in our merge queue. It's OK to leave it open, it'll be marked as merged when the commit lands from our internal repo. Until then, it's helpful for people to see it.

**Comment by rojer** [comment]
ah. i misinterpreted is as - there's an alternative internal fix. gotcha.

**Pull request merged**
