### PR TITLE
app_update: Add esp_ota_write_raw function to write pre-encrypted data (IDFGH-5583)

### PR DESCRIPTION
**Pull request by AxelLin**
Use esp_ota_write_raw instead esp_ota_write to write pre-encrypted data.

Signed-off-by: Axel Lin <axel.lin@gmail.com>

### CODE REVIEW

**Comment by AxelLin** [comment]
Hi @mahavirj 
I understand you comments in https://github.com/espressif/esp-idf/issues/6172#issuecomment-884777914.
Before introducing new "pre-encrypted" OTA image format, this function allows
existing users to implement updating pre-encrypted ota data.(https://github.com/espressif/esp-idf/issues/6172#issuecomment-881801160)
Please review if this PR is acceptable.

**Comment by mahavirj** [comment]
@AxelLin I am not quite clear on this change. So you think that application needs to take care about correct "pre-encrypted" image per flash offset per passive OTA update slot?

**Comment by AxelLin** [comment]
Hi @mahavirj 
Yes, for the use case for some customers using device in closed netowrk.
I have no choice but to implement supporting "pre-encrypted" image by taking
care the correct logic in our application side.
Actually when we do OTA in an independent partition (e.g. test partition), we
can always update image to ota1 partition and set boot from ota1. (so choose image issue).

**Comment by mahavirj** [comment]
@AxelLin Thanks for explaining. It will be difficult to accept this PR, unless we add lot of explanation in documentation (and probably application as well) to clarify usage scenario here. I would request that we wait for official approach as I had highlighted in https://github.com/espressif/esp-idf/issues/6172#issuecomment-884777914. Of course, if someone find this change useful they can always refer to PR here.

**Comment by AxelLin** [comment]
And honestly, such requirement (ota with pre-encrypted image) has been asked so many times.
Waiting for a new "pre-encrypted" OTA image format could take too much time.
(It maybe not available this year)

If this PR is not acceptable, I have no choice but to maintain my on fork of esp-idf.
Thanks for your time anyway.

**Comment by AxelLin** [comment]
> @AxelLin Thanks for explaining. It will be difficult to accept this PR, unless we add lot of explanation in documentation (and probably application as well) to clarify usage scenario here. I would request that we wait for official approach as I had highlighted in [#6172 (comment)](https://github.com/espressif/esp-idf/issues/6172#issuecomment-884777914). Of course, if someone find this change useful they can always refer to PR here.

On the second thought, by calling esp_ota_get_next_update_partition() the
firmware can easily know which encrypted ota image to download.

The only thing needs to comment or document is the feteched encrypted ota image needs
to be generated for the target partition address.

BTW, this is probably off-topic.
But I had bad experience about waitting new features ready.
e.g. regarding 802.11r support:
21 Jun 2019: we may prioritise 11r though. https://github.com/espressif/esp-idf/issues/3671#issuecomment-504357006
18 Dec 2020: 11r support will be added in future. https://github.com/espressif/esp-idf/issues/3671#issuecomment-747897503
25 Jan 2021: We are targeting 2nd quarter of 2021. https://github.com/espressif/esp-idf/issues/3671#issuecomment-766896837
Now, 11r is still not yet available. (It's more than 2 years since initial reply)

**Comment by tsctrl** [comment]
Hi @AxelLin , interested with this pr change. few question:

1. this is not related to this pr, since we not able to distribute pre encrypted fw and rely on automatic fw updates with plaintext fw (correct me). how to make sure and to secure out plaintext fw from unauthorize download and access from the server.
2. is the ota update only work with a sequence next partition boot. means after ota_0, must ota_1 then ota_0 back. is it possible for example to just always boot/use and update ota_0 update current boot partition ota_0. if fail boot factory?
2. since the issue is with the correct address, is it possible we just use simpler approach. let say i have factory and ota_0, and ota_1. so every time i do ota update, instead of automatic next ota partition. we just check the file name encrypted_ota_1.bin if no match then no update. if match then update to ota_1.bin and set as boot?
3. for the application to manage the partition how that can be done? what is application btw? is it the website to upload firmware or the fw itsef? 

thanks!

**Comment by sagb2015** [comment]
@AxelLin -  We have to keep changing priorities of the deliverables based on constantly changing demands/requirements.  For example, https://github.com/espressif/esp-idf/issues/3671#issuecomment-504357006 says that 11r will be prioritised over 11k, 11v, however, we had to make 11k and 11v ready before 11r for other prerequisites. Our intention of providing the tentative timeline is to give visibility to everyone based on the current inputs. This may or may not translate into hard deadlines for us. Hope you understand!

**Pull request closed without merging**
