### PR TITLE
Added missing MYNEWT_VAL_BLE_L2CAP_COC_MPS definition (IDFGH-3936)

### PR DESCRIPTION
**Pull request by errno**
When tried to enable L2CAP CoC in nimble stack I got an error about missing definition.
This PR adds that definition.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by prasad-alatkar** [comment]
LGTM (CC : @dhrishi )

**Review by dhrishi — APPROVED** [review]
Thanks for the PR! Looks good, we will get this merged.

**Comment by AxelLin** [comment]
It's merged by 3caa9699aef8de2dddb7d5803961c97390aa80fe.

**Comment by Alvin1Zhang** [comment]
@errno Thanks for your contribution and thanks @AxelLin  for the notes, changes merged with https://github.com/espressif/esp-idf/commit/3caa9699aef8de2dddb7d5803961c97390aa80fe

**Pull request closed without merging**
