### PR TITLE
docs(get-started): Add which as deps (IDFGH-12546)

### PR DESCRIPTION
**Pull request by arrio464**
In some cases, Arch Linux does not install 'which' in the system. 
It may cause problems like this:
```
{"message":"Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n","stack":"Error: Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n\n\tat ChildProcess.exithandler (node:child_process:420:12)\n\tat ChildProcess.emit (node:events:514:28)\n\tat maybeClose (node:internal/child_process:1091:16)\n\tat ChildProcess._handle.onexit (node:internal/child_process:302:5)","level":"error","timestamp":"2024-04-06T12:50:36.294Z"}
{"user":true,"message":"Error looking for python in system","stack":"Error: Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n\n\tat ChildProcess.exithandler (node:child_process:420:12)\n\tat ChildProcess.emit (node:events:514:28)\n\tat maybeClose (node:internal/child_process:1091:16)\n\tat ChildProcess._handle.onexit (node:internal/child_process:302:5)","level":"error","timestamp":"2024-04-06T12:50:36.296Z"}

{"message":"Cannot access filePath: cmake","stack":"Error: spawn which ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:283:19)\n\tat onErrorNT (node:internal/child_process:476:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","level":"error","timestamp":"2024-04-06T12:59:55.984Z"}
{"message":"Cannot access filePath: ninja","stack":"Error: spawn which ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:283:19)\n\tat onErrorNT (node:internal/child_process:476:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","level":"error","timestamp":"2024-04-06T12:59:56.058Z"}
{"user":true,"message":"Something went wrong while trying to build the project","stack":"Error: CMake or Ninja executables not found\n\tat uo.build (/dist/extension.js:2:1522778)\n\tat async Xs (/dist/extension.js:2:1623409)\n\tat async /dist/extension.js:2:1764720","level":"error","timestamp":"2024-04-06T12:59:56.061Z"}
```

### CODE REVIEW

**Comment by suda-morris** [comment]
This is required by https://github.com/espressif/vscode-esp-idf-extension/blob/c2f1ccf44536dc6b58a98db8a8067b61cf5103d4/src/pythonManager.ts#L355

**Review by brianignacio5 — APPROVED** [review]
LGTM

**Comment by dobairoland** [comment]
I'm not strongly against this but it opens an inconvenient precedence if we accept it.  We might start to add dependencies of dependent tools and frameworks with this logic. 

This is not required by ESP-IDF so it doesn't belong to the documentation of ESP-IDF. Other tools and frameworks which use ESP-IDF should document additional package requirements in their own documentation.

**Comment by brianignacio5** [comment]
> I'm not strongly against this but it opens an inconvenient precedence if we accept it. We might start to add dependencies of dependent tools and frameworks with this logic.
> 
> This is not required by ESP-IDF so it doesn't belong to the documentation of ESP-IDF. Other tools and frameworks which use ESP-IDF should document additional package requirements in their own documentation.

Yes it makes sense. I'm just don't know where should we add such a thing documentation because it overlaps with ESP-IDF prerequisites. A better solution would be to avoid the use of which/where altogether.

**Pull request closed without merging**
