### PR TITLE
BLE GATTS and GAP callback getter methods (IDFGH-11703)

### PR DESCRIPTION
**Pull request by zrgravity**
Allows user methods to access the BLE GATTS and GAP callbacks, if set. This allows multiple callback to be used, for instance, when there are multiple services and profiles.

### CODE REVIEW

**Comment by zhp0406** [comment]
thanks for your MR，I will check it.

**Comment by zhp0406** [comment]
In the example (https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/bluedroid/ble/gatt_server/main/gatts_demo.c#L732), multiple profiles coexist, and the use of the get method is not mandatory. Can you elaborate on the scenarios where the use of the get method is necessary?

**Comment by zhp0406** [comment]
Your submission has been accepted. After testing, it can be used on GitHub. This issue can be closed now.
commit will comming soon：
be47da19628967449635c9042306b861a2fe3ed8
6bc5b0069f980dc9868942df66bd914d75fd4299

**Comment by Alvin1Zhang** [comment]
Thanks for contribution again, changes have been merged.

**Pull request closed without merging**
