### PR TITLE
Fix init MCPWM Fault line via config struct (IDFGH-3473) (IDFGH-3539)

### PR DESCRIPTION
**Pull request by Wielebny666**
nothing more ;-)

### CODE REVIEW

**Comment by Wielebny666** [comment]
fix this problem: https://github.com/espressif/esp-idf/issues/5433

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by Alvin1Zhang** [comment]
Thanks for contribution and sorry for late updates, please refer to https://github.com/espressif/esp-idf/commit/c58fd3df2904b8ecf0531b812bf6917b5ff62cb7. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks again for your contribution.

**Pull request closed without merging**
