### PR TITLE
Stop WiFi provisioning in the esp_event thread instead of creating new thread (IDFGH-8966)

### PR DESCRIPTION
**Pull request by Barabas5532**
When WiFi provisioning is stopped asynchronously (`wifi_prov_mgr_stop_provisioning`), a new thread is created using 4096 bytes from the heap:

https://github.com/espressif/esp-idf/blob/edd815af2e7d541b25ff3a74c59a7fe0612df42d/components/wifi_provisioning/src/manager.c#L674

I've changed this to run the `prov_stop_task` in the `esp_event` thread, reducing the heap usage of the application.

The PR is marked as draft because some of the comments in `manager.c` are now outdated. Please let me know if there is any interest in merging this change, then I will get it ready for a merge.

### CODE REVIEW

**Comment by Barabas5532** [comment]
Tested this with my project: https://github.com/ShrapnelDSP/ShrapnelMonorepo/commit/d351c0c538c958731123e96cbf626d30912aa34b

- start with Wi-Fi not provisioned
- entered the wrong password during provisioning
- retry with the correct password
- log the minimum free heap heap during the websocket upgrade callback

Before this change, the average of three runs was 4141. After, it is improved to 6952.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by laukik-hase** [comment]
Hello, @Barabas5532!

Thanks for your contribution! The pull request looks good to me. You can update the pull request with the rest of your changes and mark it as ready.

**Comment by laukik-hase** [comment]
Hello, @Barabas5532!

Any updates for this PR?

**Comment by laukik-hase** [comment]
Hello, @Barabas5532!

Could you please share if you have any updates for this PR? If not, I will take this up internally.

**Comment by laukik-hase** [comment]
sha=5cdf4236585e19bba5c756700bcf4e39336df15c

**Comment by laukik-hase** [comment]
Merged with https://github.com/espressif/esp-idf/commit/005196d86d59e22ac0ad9a942cd9db4ad32994e7

**Pull request closed without merging**
