### PR TITLE
Update the rmt documentation (IDFGH-2837)

### PR DESCRIPTION
**Pull request by raldone01**
State which functions require the rmt driver to be installed.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@raldone01 Thanks for the contribution.

**Comment by suda-morris** [comment]
Thanks @raldone01 for your contribution to esp-idf. We will merge it ASAP.

**Comment by raldone01** [comment]
Registering a custom interrupt seems broken. I will reopen this as an issue.

**Comment by projectgus** [comment]
Hi @raldone01,

I don't see the issue, did you end up opening one?

Thanks for sending this PR in any case. After looking at this, we've determined that these were accidental breaking changes in the driver API. The IDF v4.0 API doesn't require pre-installation.

So our plan at the moment is to fix the behaviour to make IDF v4.0.

**Comment by raldone01** [comment]
I forgot to open a issue. Should I still open one? (For the time being I copied the rmt.h and rmt.c from 4.0 over 4.1 because my application uses the netif abstraction.)

**Comment by projectgus** [comment]
@raldone01 We're planning to fix the "install driver before using this function" breaking changes already. If you found another bug that you think might not be covered by this, an issue with the details would be great - thanks.

**Pull request closed without merging**
