### PR TITLE
feat(ulp): Add optional -msave-restore for RISC-V (U)LP targets (IDFGH-12976)

### PR DESCRIPTION
**Pull request by andylinpersonal**
Possibly useful for larger apps on C6 and P4's LP core.

### CODE REVIEW

**Comment by 0xjakob** [comment]
@andylinpersonal Thanks for the suggestion, we'll take a look at this.

**Comment by sudeep-mohanty** [comment]
Thanks for the contribution @andylinpersonal. This could be a useful addition to the ULP/LP Core subsystem. The changes generally LGTM. I've left some minor comments to address. Additionally, it would be nice to add some documentation about it in the [ULP RISC-V](https://github.com/espressif/esp-idf/blob/master/docs/en/api-reference/system/ulp-risc-v.rst) and [LP Core](https://github.com/espressif/esp-idf/blob/master/docs/en/api-reference/system/ulp-lp-core.rst) reference.

Do let us know if you'd have time to address the comments or else I could help with the re-work as well. Thanks!

**Comment by andylinpersonal** [comment]
Hi @sudeep-mohanty:
I'm willing to help to address the comments. I'll also push the updated documentation pages tomorrow.

**Comment by andylinpersonal** [comment]
Related documentation has been updated.

**Comment by ESP-Marius** [comment]
@andylinpersonal We've pushed a feature that should hopefully allow achieving stuff like this much easier for users.

You can see an example [here])https://github.com/espressif/esp-idf/blob/master/examples/system/ulp/lp_core/build_system/main/ulp/CMakeLists.txt)

I think with that we'll consider this ticket closed, feel free to reopen it if you still think this option should be available by default for the lp-core.

Or open a new ticket if you are unhappy/have any requests with regards to the ULP build-system.

**Pull request closed without merging**
