### PR TITLE
Add missing brace in Gatt_Server_Example_Walkthrough.md (IDFGH-11590)

### PR DESCRIPTION
**Pull request by Harrisonust**

### CODE REVIEW

**Comment by zhp0406** [comment]
Thank you for your report. In the future, we will optimize the documents.

**Comment by esp-zhp** [comment]
3a9e05984ae722f76ff0f91626502db4b2a126e8

**Comment by esp-zhp** [comment]
commit 3a9e05984ae722f76ff0f91626502db4b2a126e8     docs(ble/bluedroid): Optimize BLE example documentation
commit 86713a6946cf91c9d46eeb73935da39884efec13     docs(ble/bluedroid): Optimize BLE example documentation for getting characteristic
commit 0d2929358fca4507f1e8d08972c067aacd20ed90     docs(blufi): Optimize documentation for Blufi example
commit f9e45f98070321c79c78f1df8725297fec841769     docs(ble/bluedroid): Optimize BLE example for setting advertising data
commit 3e98408b9277b526371396beb10f2d1ba43f0767     docs(ble/bluedroid): Optimize documentation for BLE connection parameter updates
commit bce1715dfdfe791ab950f7fcb94d537b74c90025     fix(ble/bluedroid): Optimize BLE documentation comments to comply with Doxygen syntax
commit f81286382722e67bbcafe1d994bb3bcfac35b437     fix(ble/bluedroid): Optimize the BLE  documentation
commit ee4d4f1d358e7d48dfb53d79af10cf1fa26a4afa     docs(ble/bluedroid): Optimize documentation for BLE duplicate scan
commit 96626cb11074656c1adb3e6e05ceed043daf0af0     fix(bt/bluedroid): Update ble ibeacon example document
commit cfd84e654c2c7da2b8bc7b547889216cde4542ae     fix(bt/bluedroid): Update ble gattc gatts coex example
commit a5a7e60ad0bd0b00839310b6d28a87ae80fd0e94     docs(bt/bluedroid): Update ble example document

**Comment by Alvin1Zhang** [comment]
Thanks for contribution again.

**Pull request closed without merging**
