### PR TITLE
Non-mesh ip network example (IDFGH-6505)

### PR DESCRIPTION
**Pull request by wizche**
This is an attempt to "fix" #7528

EDIT2 (17.01.2021): Well I was completely wrong so here my findings after investigating this more.

Adapting the `internal_communication` wont work because even if we dont start the DHCP server/client the request are not relayed to the root node and therefore we cannot use the root node as the only DHCP server. As @shenjun7 pointed out _Root as the only dhcp server to allocate IP to non-mesh nodes requires a lot of changes, we will update in the future_.
Starting a DHCP server on every node is also not feasible since we will have duplicates IP across the (mesh) network. 

So basically the only solution I could find is based on my initial idea of adapting `ip_internal_network`. The idea is to have the entrypoint node (the one where non-mesh device will connect to) to reconfigure its soft-ap part to expose a different SSID.
Specifically I introduce the `ap` console command that will reconfigure the node in the following way:
- Reconfigure SoftAP to expose a new SSID that will be used by non-mesh clients
- Enable DHCP server on SoftAP
- Enable PNAT on the SoftAP interface (traffic from the non-mesh clients is NATed and forwarded to ST and therefore to the root node)

Even though this works, I experience major connectivity issues, not only from the non-mesh device but from the node themselves. I see packet drops, frame size error (when encapsulating into the mesh packet) and general instability. 
You can check the README in `nonmesh_ip_internal_network` for additional details.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by wizche** [comment]
I kept the `nonmesh_ip_internal_network` example as lesson learned but if you think this branch will be merged without it I will just remove it (or maybe open another PR just for that?)

**Comment by shenjun7** [comment]
Thanks for your contribution on ESP-MESH, we will check your code and give you feedback soon.

**Comment by zhangyanjiaoesp** [comment]
@wizche Can you please rebase the PR and remove the `nonmesh_internal_communication` example ?

**Comment by Sherry616** [comment]
Closing due to lack of reply. Feel free to submit a newer PR if you'd still prefer us to consider these changes. Thanks.

**Pull request closed without merging**
