### PR TITLE
docs: fix typo in esp_http_client_init return type (IDFGH-8244)

### PR DESCRIPTION
**Pull request by ChromaMaster**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by suda-morris** [comment]
sha=8f5660b15021dadc6c9f2e5c91f56f387b5d7758

**Comment by hmalpani** [comment]
@ChromaMaster please sign the CLA. Thanks!

**Comment by ChromaMaster** [comment]
@hmalpani Done, sorry for the delay.

**Pull request merged**
