### PR TITLE
(vfs) fix wrong args (IDFGH-5692)

### PR DESCRIPTION
**Pull request by cc-caixf**
I think this is a mistake, so I creat a PR.
Mayebe I was wrong....

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by negativekelvin** [comment]
Looks right. While you're there you should move the success message inside the previous block https://github.com/espressif/esp-idf/pull/7413/files#diff-59a3aec22256287ff7b608d270aea0d825d4074df536a58cc57b367bde1b9132R160

**Review by dobairoland — APPROVED** [review]
Thank you for the fix.

**Comment by AxelLin** [comment]
@dobairoland @Alvin1Zhang 
Is this PR still valid?
This looks like a bug fix and got approved, I'm wondering is anything block this PR?

**Comment by dobairoland** [comment]
@AxelLin We are sorry for the delay. I have reviewed it and it looks good to me. Unfortunately, the internal test got delayed.

**Pull request closed without merging**
