### PR TITLE
Fix compilation warnings about portmacro being already define. (IDFGH-3836)

### PR DESCRIPTION
**Pull request by csobrinho**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by Campou** [comment]
Hi @csobrinho 

Thanks for the bugfix. I will submit a MR for this internally, and it will be synced to Github later.

Thanks.

**Comment by Campou** [comment]
Hi @csobrinho 

Thanks for the bugfix. I will submit a MR for this internally, and it will be synced to Github later.

Thanks.

**Comment by Alvin1Zhang** [comment]
@csobrinho Thanks for your contribution, changes merged with https://github.com/espressif/esp-idf/commit/03f5d2fec8984a112dd1e70b2fbcf5daf26d0a83.

**Pull request closed without merging**
