### PR TITLE
FIXES ISSUE #5637 (IDFGH-3712)

### PR DESCRIPTION
**Pull request by DaividFrank**
If I somehow missed any logs please let me know and I'll be happy to fix them.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by projectgus** [comment]
Noting this in relation to #5637 (to create the cross-link).

@DaividFrank After discussing this internally, we may fix it in another way as we have a separate configuration setting for disabling logs already. Instead we'll make sure no instance of `__FILE__` is incorrectly passed to the logging mechanism (we have the log tag for exactly this reason).

The PR & the linked issue will be updated once this is fixed. Thanks again.

**Comment by DaividFrank** [comment]
@projectgus I'll be more than happy to do it if possible =]

**Comment by projectgus** [comment]
@DaividFrank Thanks for the offer but as it's a small change I think we can make it internally as well, and then merge it. Thanks for drawing this to our attention in the first place!

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, changes have been merged with https://github.com/espressif/esp-idf/commit/37cd6249d8e9d32fd835a18133bf80ebb2cc7109. Thanks.

**Pull request closed without merging**
