### PR TITLE
Fix eclipse build error on Windows: “UnicodeDecodeError: 'ascii' codec can't decode byte” (IDFGH-4693)

### PR DESCRIPTION
**Pull request by patrykkrz**
After commit 2e9561d252b7a84bfe2644f17b2f58c747b19416 build in Eclipse was failed.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by dobairoland** [comment]
Hi @patrykkrz. Thank you for this. Please sign the Contributor License Agreement.

**Comment by patrykkrz** [comment]
> Hi @patrykkrz. Thank you for this. Please sign the Contributor License Agreement.

Done.

**Comment by dobairoland** [comment]
Great! Thanks!

This will be closed when the commit gets to the master branch. Will be backported to release branches as well. All  commits will reference this PR.

**Pull request closed without merging**
