### PR TITLE
Add possibility to use cert bundle , e.g. x509, to websocket client (IDFGH-10041)

### PR DESCRIPTION
**Pull request by ghost**
- Mimic in esp_websocket_client_config_t how the variable crt_bundle_attach is used in esp_http_client_config_t

### CODE REVIEW

**Comment by gabsuren** [comment]
@martinsmoofit Thank you for contribution, starting from version `5.0` `esp_websocket_client` was migrated from [`esp-idf`](https://github.com/espressif/esp-idf) to [`esp-protocols`](https://github.com/espressif/esp-protocols), could you please move this PR to [`esp-protocols`](https://github.com/espressif/esp-protocols) so we can proceed?

**Comment by martinsmoofit** [comment]
Hi, @gabsuren. The feature already exists in https://github.com/espressif/esp-protocols, https://github.com/espressif/esp-protocols/pull/49, but I can't find that it has been backported to v.4.4 as suggested in the comments.

**Comment by martinsmoofit** [comment]
@gabsuren tbh I didn't know the feature existed in 5.0 before the PR. I added it to v4.4 because that is the version we are currently working with in out company. So no, I don't have any strong reasons for backporting the feature.

**Comment by gabsuren** [comment]
@martinsmoofit thank you for the response! Accordingly  closing the issue

**Pull request closed without merging**
