### PR TITLE
HTTPS OTA: Removed unnecessary free() (IDFGH-1209)

### PR DESCRIPTION
**Pull request by gregjesl**
Closes https://github.com/espressif/esp-idf/issues/3504

### CODE REVIEW

**Comment by mahavirj** [comment]
Good catch! This was regression introduced with recent refactoring from this component. @jitin17 Please help to check.

**Comment by chegewara** [comment]
@mahavirj https://github.com/espressif/esp-idf/issues/3504#issuecomment-494614049

**Comment by jitin17** [comment]
@gregjesl Thanks for pointing this out. I will get this merged as soon as possible

**Comment by mahavirj** [comment]
@gregjesl Fixed with https://github.com/espressif/esp-idf/commit/7fbedb1ba3849464921f6514d51686be769f454d (bit modified version to take care of all possible scenarios). Also included in example level test to catch such regressions upfront.

**Pull request closed without merging**
