### PR TITLE
Documentation clean up

### PR DESCRIPTION
**Pull request by krzychb**
Preview: http://esp-idf-fork.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by projectgus** [comment]
> This looks great, I'll cherry-pick it into our internal merge queue.

Oops, I hadn't noticed that this was in an PR already (I got notified by the commit itself). Will leave it as part of this pull request.

I also noticed that build_system.rst should probably have been called build-system.rst, we're using hyphens everywhere else. Not an urgent thing to fix, but if you feel like adding it to this PR that would be great. :)

**Comment by projectgus** [comment]
This PR is in the internal review/merge queue.

**Comment by igrr** [comment]
Thanks @krzychb, except for the update history commit, this has been merged in 383d987.

**Comment by krzychb** [comment]
Instead of "update history" I propose to add a link to https://github.com/espressif/esp-idf/releases (just above the TOC). 

No extra updating would be required as for "update history" and readers will be provided with quick link to information what's new.

**Pull request closed without merging**
