### PR TITLE
EspNimbleGattWrite.c (IDFGH-7630)

### PR DESCRIPTION
**Pull request by Alexx-Z**
The NimBLE based Gatt Write solution for ESP32 in ESP IDF environment

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by rahult-github** [comment]
Hi @ESP-BLE-Devices  , can you please comment as to why the existing blecent / bleprph examples which showcases demo application for gatt client / server usage not enough ?

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, feel free to reopen with more updates.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, feel free to reopen with more updates.

**Pull request closed without merging**
