### PR TITLE
Fix regression in i2c_master_read() which rejected all data lentghs.

### PR DESCRIPTION
**Pull request by PerMalmberg**

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks @PerMalmberg . I've pushed these into our internal review & merge queue.

For future reference, fixes like these are very welcome but please open separate PRs for unrelated issues/fixes.

**Comment by projectgus** [comment]
Ah, I see that the commit for logging was maybe introduced here by mistake and duplicated in #1444. As these are very small fixes I'll delete the other PR and we'll try to merge these both as one.

**Comment by PerMalmberg** [comment]
@projectgus Oh, GitHub doesn't take into consideration what commit the PR was created from. Good to know. Thanks for not making me redo the PR. :)

**Comment by projectgus** [comment]
Thanks again @PerMalmberg  :)

> Oh, GitHub doesn't take into consideration what commit the PR was created from. Good to know. Thanks for not making me redo the PR. :)

Github compares the branch the PR originates from (ie your branch on Github) to the branch you're merging into (ie ESP-IDF master). So any commits in the first which aren't in the second, are added to the PR. If you update the branch, it updates the PR.

**Pull request merged**
