### PR TITLE
esp_ping - Document that timeout units are in milliseconds

### PR DESCRIPTION
**Pull request by chmorgan**
Remove 1000 multiplier from esp_ping_set_target() parameters that define time

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks for bringing this to our attention, @chmorgan .

I agree that milliseconds seems to make more sense here. The dilemma is whether to document the current units (seconds) and leave the behaviour unchanged, or change the behaviour and risk breaking existing code. I've asked my colleague who originally wrote this API for their opinion on this.

**Comment by chmorgan** [comment]
Thanks for taking a look st it.

Seconds isn’t a very good unit for a network operation like this. I’m
guessing there are few users of this code. The example I found on the forum
looked like it was assuming milliseconds so perhaps they didn’t test it.

**Comment by liuzfesp** [comment]
LGTM

**Comment by projectgus** [comment]
Thanks @liuzfesp . I've pushed this into our internal review & merge queue.

**Comment by chrta** [comment]
@igrr @projectgus Any chance this change gets cherry-picked into the branch release/v3.0? A ping timeout and delay time in milliseconds make a lot more sense, e.g. during production testing.

**Comment by projectgus** [comment]
Hi @chrta ,

Sorry I didn't reply to you earlier. Unfortunately backporting this to the release branch would change the behaviour of the ping API, which we're reluctant to do in a bugfix point release.

It will be available in the v3.1 release (or you can cherry-pick it yourself if needed, I don't think it will lead to any problems updating IDF in the future.)

Angus

**Pull request merged**
