### PR TITLE
Add mDNS miss comment (IDFGH-6445)

### PR DESCRIPTION
**Pull request by Caffreyfans**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by b1ackviking — APPROVED** [review]

**Comment by suda-morris** [comment]
sha=08e081340d9d76d1244e9f2dc527e5ae370b1fbe

**Comment by laukik-hase** [comment]
This PR was merged in commit 08e081340d9d76d1244e9f2dc527e5ae370b1fbe.

**Comment by Caffreyfans** [comment]
Thanks a lot.

**Pull request closed without merging**
