### PR TITLE
CMake: Add ESP_PLATFORM to build environment.

### PR DESCRIPTION
**Pull request by PerMalmberg**
As first discussed in [this forum thread](https://www.esp32.com/viewtopic.php?f=13&t=7535&p=32533#p32533), the ESP_PLATFORM define is missing during configuration and build when building with CMake.

### CODE REVIEW

**Comment by PerMalmberg** [comment]
Just realized that GitHub updates pull requests when new changes are added to the same branch, sorry about that. Both commits are however related to the same forum thread.

**Comment by PerMalmberg** [comment]
Just merged upstream/master into my fork to resolve the conflict.

**Comment by projectgus** [comment]
Hi @PerMalmberg ,

Thanks for submitting this, sorry for the extended delay in getting back to you.

This looks good to me. The only sticking point is we are about to merge Generic CMake build support, which should make sharing CMake code between IDF and non-IDF CMake projects much easier. However, those changes will conflict with this PR.

This PR is still useful though, because there may be situations where CMake libraries or other projects want to test at CMake runtime whether they are running inside IDF or inside a generic CMake project.

Once we merge the Generic CMake support (next few days), I'll cherry-pick this PR onto our master branch and resolve the conflicts, and we can merge it that way.

**Comment by PerMalmberg** [comment]
Now that the new CMake changes have been merged, could these changes please be cherry picked into master, @projectgus ?

**Comment by projectgus** [comment]
@PerMalmberg Yes, sorry for the hold-up. We got stuck discussing whether we should deprecate the `ESP_PLATFORM` name now that most variables are being namespaced as `IDF_xxx`. This will cherry-picked (either using this variable name or a more consistent one), soon.

**Comment by PerMalmberg** [comment]
@projectgus Have you decided on the variable name yet?

**Comment by projectgus** [comment]
After a long discussion, we're going to stick with ESP_PLATFORM for now. PR should be finally merged shortly... thanks for staying patient.

**Comment by PerMalmberg** [comment]
> After a long discussion, we're going to stick with ESP_PLATFORM for now. PR should be finally merged shortly... thanks for staying patient.

And thank you for the update. Looking forward to be able to compile for both ESP and Linux again.

**Comment by PerMalmberg** [comment]
@projectgus I'm closing this since your commits resolves this PR.

**Comment by projectgus** [comment]
@PerMalmberg Thanks for that, and thanks for your patience while we worked through this change.

**Pull request closed without merging**
