### PR TITLE
Linenoise don't return NULL on 0 length input (IDFGH-2869)

### PR DESCRIPTION
**Pull request by MadnessASAP**
Linenoise should only return NULL if there's been an error on input or if EOF is reached (user enters Ctrl-D)  0 length inputs are still valid and should be treated and returned as such.

### CODE REVIEW

**Comment by igrr** [comment]
Does this change mean that empty lines will be added to history? If yes, there probably needs to be an additional check to avoid doing that.

**Comment by MadnessASAP** [comment]
> Does this change mean that empty lines will be added to history? If yes, there probably needs to be an additional check to avoid doing that.

It does not, adding to history is still controlled via linenoiseHistoryAdd().  It's possible for a downstream developer to inadvertently add 0 length strings to the history if they don't check the string returned by linenoise() against strlen().  Fortunately linenoiseHistoryAdd() already partially mitigates that by not adding history lines that are identical to the previous entry, that is repeatedly pressing enter won't fill the history buffer with more than 1 blank line.

I'll add that my proposed behaviour is in line with the upstream linenoise library behaviour.

**Comment by Alvin1Zhang** [comment]
@MadnessASAP Thanks for the contribution.

**Comment by igrr** [comment]
Thanks for explaining! In this case there probably needs to be an extra check in the example before calling linenoiseHistoryAdd, so that empty lines don't get added to history at all.

That said, there is a minor concern that this would change the behavior of existing apps which used the console example as their base. It is easily fixable, but could be a breaking change for some nevertheless. So we may need to add some Kconfig option to allow reverting the old behavior.

**Comment by MadnessASAP** [comment]
I've touched up the example to filter blank lines and added a Kconfig to default to the old behavior

**Comment by igrr** [comment]
@MadnessASAP The PR was merged with a follow-up change to make the behavior run-time configurable (instead of the Kconfig option), since the cost of run-time configuration in this is quite low. Sorry for the slow turnaround and thanks again for contributing!

**Pull request closed without merging**
