### PR TITLE
Add cert/key length options to esp_http_client (IDFGH-4752)

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64  Thanks for your contribution.

**Review by shubhamkulkarni97 — APPROVED** [review]

**Comment by 0xFEEDC0DE64** [comment]
Ok is this PR already in consideration? Are any questions open? Can I help somehow to get this merged?

**Comment by shubhamkulkarni97** [comment]
Hi @0xFEEDC0DE64,
This PR is in consideration, I'll update when it gets merged internally. Thanks

**Comment by shubhamkulkarni97** [comment]
@0xFEEDC0DE64 Could you share the context in which this fix is required? Or an example that fails without this fix?

**Comment by 0xFEEDC0DE64** [comment]
my keys are coming from an encrypted partition and are not necessary 0-terminated. I applied the same api as for other client key auth parameters in esp-idf. Do you think it is not useful to specify the length in advance and skip an unnessecary strlen?

**Comment by shubhamkulkarni97** [comment]
@0xFEEDC0DE64 Changes from this PR are merged internally. These changes will be available on GitHub once all internal checks are passed.

**Pull request closed without merging**
