### PR TITLE
ESP32-S3 page-table initialized twice (IDFGH-8492)

### PR DESCRIPTION
**Pull request by svenbieg**
mmu_ll_unmap_all() is called twice in mmu_hal_init(), but mmu_id is ignored in mmu_ll.h.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by suda-morris** [comment]
Hi @svenbieg would you please squash the commits in this PR? **four** commits are too much for the small fix.

**Comment by svenbieg** [comment]
I'm sorry, i don't know anything about "squashing".


---- suda-morris schrieb ----


Hi @svenbieg<https://github.com/svenbieg> would you please squash the commits in this PR? four commits are too much for the small fix.

**Comment by svenbieg** [comment]
You should have gotten a compiler-warning already! ;-)

**Comment by svenbieg** [comment]
The question is if there are any systems on a chip with two page-tables? In a multi-tasking environment any core is able to take over the same task. How should this be possible with different page-tables?

**Comment by svenbieg** [comment]
I'm satisfied with one page-table already.

**Comment by svenbieg** [comment]
I think i know what You mean: I'd like to undo changes i don't like anymore (squashing?). I've tried, but in case i have to commit Your changes too. You can try to contact Microsoft, i didn't have any success with it. I'm really sorry about this, the only thing i'm trying to do is taking over Your kernel. I have to make a compliment at this point because i couldn't find any bugs by now.
But two page-tables? What is this?

**Pull request closed without merging**
