### PR TITLE
NVS: add support for i16, u64, i64 types to NVS partition generation tool (IDFGH-2227)

### PR DESCRIPTION
**Pull request by bbinet**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@bbinet Thanks for the contribution.

**Comment by bbinet** [comment]
up?

**Comment by igrr** [comment]
Hi @bbinet, sorry for the delay. The commits have been cherry-picked into `master`, and should show up on Github soon. Will update once again when this happens.

**Comment by bbinet** [comment]
Thank you @igrr

**Comment by shivani-tipnis** [comment]
Hi @bbinet 
The changes are up on Github.
https://github.com/espressif/esp-idf/commit/cab895f45996e312e7594fcd8bf47731c29336c3#diff-cb3dd88d88d6fd7bc7482a58b07995eb
https://github.com/espressif/esp-idf/commit/70840158844131c1dd2afa5b5ec3361ea85ca0c0#diff-cb3dd88d88d6fd7bc7482a58b07995eb
Thanks

**Comment by Alvin1Zhang** [comment]
@bbinet Thanks for contribution.

**Pull request closed without merging**
