### PR TITLE
SPI Release Tweak (IDFGH-7584)

### PR DESCRIPTION
**Pull request by meawoppl**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by meawoppl** [comment]
@cibomahto got a second to synopsize?

**Comment by Maksons** [comment]
@meawoppl 
Sorry, question from side viewer:
Could you descripe idea behind this patch?

**Comment by KaeLL** [comment]
@Maksons seconded. What's the goal here?

**Comment by negativekelvin** [comment]
Possibly to reduce overhead by not calling xQueueSendFromISR and not yielding

**Comment by meawoppl** [comment]
Apologies, this is @cibomahto 's work, I was just trying to be helpful by making a PR of it. I think he will chime in shortly.

**Comment by KaeLL** [comment]
I think @negativekelvin is right.
This is a good one. Will test it later. Nice job, @cibomahto.

**Comment by KaeLL** [comment]
@ginkgm care to take a look?

**Comment by ginkgm** [comment]
This is a good one, I think we will accept this

**Pull request closed without merging**
