### PR TITLE
add fn to return user ctx for websocket (IDFGH-6102)

### PR DESCRIPTION
**Pull request by udaik**

### CODE REVIEW

**Comment by ESP-YJM** [comment]
Hi @udaik, thanks for your contribution. Could you please attach the usage example of this API here.

**Comment by Alvin1Zhang** [comment]
@udaik Thanks for your contribution again, would you please help update on https://github.com/espressif/esp-idf/pull/7780#issuecomment-956090437? Thanks.

**Comment by Alvin1Zhang** [comment]
@udaik Thanks for your contribution again, would you please help update? Thanks.

**Comment by Alvin1Zhang** [comment]
@udaik Thanks for your contribution again, will close due to short of feedback, feel free to reopen with more updates.

**Pull request closed without merging**
