### PR TITLE
Add export and install scripts for fish shell (IDFGH-2899)

### LINKED ISSUE #4459: export.sh fail on shell fish (IDFGH-2324)
----------------------------- Delete below -----------------------------

If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at esp32.com instead.

INSTRUCTIONS
============

Before submitting a new issue, please follow the checklist and try to find the answer.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

If the issue cannot be solved after the steps before, please follow these instructions so we can get the needed information to help you in a quick and effective fashion.

1. Fill in all the fields under **Environment** marked with [ ] by picking the correct option for you in each case and deleting the others.
2. Describe your problem.
3. Include [debug logs on the monitor](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/idf-monitor.html#automatically-decoding-addresses) or the [coredump](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/core_dump.html).
4. Provide more items under **Other items if possible** can help us better locate your problem.
5. Use markup (buttons above) and the Preview tab to check what the issue will look like.
6. Delete these instructions from the above to the below marker lines before submitting this issue.

----------------------------- Delete above -----------------------------

## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v1
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): cv4.1-dev-1086-g93a8603c5

- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): v4.1-dev-1086-g93a8603c5
- Operating System:     Linux (Debian Buster)
- Power Supply:         USB

## Problem Description

I'm using [FISH SHELL](https://fishshell.com/)

Following the steps from [Get Started](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#get-started-get-esp-idf), on Step 4 - Setup environment variables, on [Linux](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#id5) 
The follow line, from step above:

```
. $HOME/esp/esp-idf/export.sh
```

Issues a error
```Shell
. $HOME/esp/esp-idf/export_fish.sh                                       23:53
~/esp/esp-idf/export_fish.sh (linha 1): Unexpected ')' found, expecting '}'
# This script should be sourced, not executed.

function realpath_int() {
    wdir="$PWD"; [ "$PWD" = "/" ] && wdir=""
    arg=$1
    case "$arg" in
        "/"*) scriptdir="${arg}";;
^
do arquivo ~/esp/esp-idf/export_fish.sh
	chamado na linha 359 do arquivo “/usr/share/fish/config.fish”

na função “.”
	chamado na entrada padrão
```

### PR DESCRIPTION
**Pull request by eliabieri**
I added a fish shell version of the export.sh and install.sh scripts.
This will close #4459 

Looking forward to your feedback.
Cheers

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@eliabieri Thanks for your contribution.

**Comment by suda-morris** [comment]
Nice Job! @eliabieri  This PR really helps many fish users. We will merge is ASAP, it's already in our internal review list.

**Comment by eliabieri** [comment]
Since this PR got closed, will it not be merged after all? Previously I was provided the information that the PR is already on a internal review list. 
Thanks

**Comment by igrr** [comment]
@eliabieri The PR was cherry-picked as commit https://github.com/espressif/esp-idf/commit/0c1577fdcde3500e0652c28186311c70eeaca7bd. Unfortunately Github doesn't recognize cherry-picked PRs as "merged"...

**Pull request closed without merging**
