### PR TITLE
Add DTLS support to libcoap using MbedTLS (IDFGH-1018)

### PR DESCRIPTION
**Pull request by mrdeep1**
This update supports DTLS, TLS is a future TODO

components/coap/CMakeLists.txt:
components/coap/component.mk:

Add in the new files that have to be built
Replace libcoap/src/coap_notls.c with libcoap/src/coap_mbedtls.c

components/coap/libcoap:

Update the version to include the current version for supporting MbedTLS

components/coap/port/coap_debug.c:
components/coap/port/coap_mbedtls.c:
components/coap/port/include/coap/coap_dtls.h:

New port files for DTLS

components/coap/port/include/coap_config_posix.h:

Include building with MbedTLS

examples/protocols/coap_client/README.md:
examples/protocols/coap_client/main/CMakeLists.txt:
examples/protocols/coap_client/main/Kconfig.projbuild:
examples/protocols/coap_client/main/coap_client_example_main.c:
examples/protocols/coap_client/main/component.mk:

Update CoAP client to support DTLS

examples/protocols/coap_client/main/coap_ca.pem
examples/protocols/coap_client/main/coap_client.crt
examples/protocols/coap_client/main/coap_client.key

New PKI Certs for CoAP client (copied from wpa2_enterprise example)

examples/protocols/coap_server/README.md:
examples/protocols/coap_server/main/CMakeLists.txt:
examples/protocols/coap_server/main/Kconfig.projbuild:
examples/protocols/coap_server/main/coap_server_example_main.c:
examples/protocols/coap_server/main/component.mk:

Update CoAP server to support DTLS
Change "no data" to "Hello World!" to prevent confusion

examples/protocols/coap_server/main/coap_ca.pem
examples/protocols/coap_server/main/coap_server.crt
examples/protocols/coap_server/main/coap_server.key

New PKI Certs for CoAP server (copied from wpa2_enterprise example)

See Issue #1379

### CODE REVIEW

**Comment by mahavirj** [comment]
@mrdeep1 Is it possible to rebase this PR with upcoming `mbedtls` support from libcoap? We would love to have this integrated to IDF as soon as possible.

**Comment by mrdeep1** [comment]
@mahavirj At present there is a backlog of things waiting to be merged into libcoap ahead of the mbedtls PR which could take some time to clear.  In particular, I would like to see https://github.com/obgm/libcoap/pull/335 merged in which does affect the mbedtls code.

The mbedtls support does needs to be in a generally available version of libcoap to support fixing any subsequent issues found, rather than in a special clone that only I can maintain.

That said, I should be able to find the time to rebase this PR using MbedTLS instead of TinyDTLS when libcoap has caught up with mbedtls.

**Comment by mrdeep1** [comment]
@mahavirj It may be worth considering getting this PR merged so that you at least have PSK support in place for libcoap short term.  Then when MbedTLS is available in libcoap, we can then switch the underlying (D)TLS library and possibly set up a compile time option to chose between the (D)TLS libraries of CoAP.

**Comment by negativekelvin** [comment]
Doesn't Mbedtls use huge static buffers for dtls handshake reassembly?  Do you think that is practical on esp32?  Is there a way to enable support for dtls with psk only in mbedtls?

**Comment by mahavirj** [comment]
> @mahavirj It may be worth considering getting this PR merged so that you at least have PSK support in place for libcoap short term. Then when MbedTLS is available in libcoap, we can then switch the underlying (D)TLS library and possibly set up a compile time option to chose between the (D)TLS libraries of CoAP.

@mrdeep1 We may not be able to address all requirements from https://github.com/espressif/esp-idf/issues/1379 with this PR, hence took alternate approach to help and upstream mbedtls support in libcoap. I think we can wait for some time (and allow for things to settle as you mentioned above), if it doesn't converge maybe we can fork and maintain patches on libcoap on our side.

> Doesn't Mbedtls use huge static buffers for dtls handshake reassembly? Do you think that is practical on esp32? Is there a way to enable support for dtls with psk only in mbedtls?

@negativekelvin We have done some testing with mbedtls internally, both client and server can be supported with DTLS (memory utilization looks reasonable as well).

**Comment by mrdeep1** [comment]
@mahavirj @jitin17 Initial MbedTLS update, using port copies of the necessary files to get things moving. Initial testing looks OK, but could well have missed things in my qemu emulation of esp32.

**Comment by jitin17** [comment]
@mrdeep1 Thank you for your contribution. This PR has been added to our internal review queue and will try to accept it as soon as possible.

**Comment by mrdeep1** [comment]
@jitin17 components/coap/port/coap_io.c should no longer be there (conflict was reported in the checks).  The following update has just been pushed to allow original libcoap/src/coap_io.c to compile with the latest esp-idf code

````
diff --git a/components/coap/port/include/coap_config_posix.h b/components/coap/port/include/coap_config_posix.h
index 19a855e..dc11660 100644
--- a/components/coap/port/include/coap_config_posix.h
+++ b/components/coap/port/include/coap_config_posix.h
@@ -28,6 +28,7 @@
 #define HAVE_ARPA_INET_H
 #define HAVE_TIME_H
 #define HAVE_NETDB_H
+#define HAVE_NETINET_IN_H
 
 #define IPV6_PKTINFO IPV6_V6ONLY
````

**Pull request closed without merging**
