### PR TITLE
lwip: Add Kconfig option ETHARP_SUPPORT_VLAN to accept tagged packets (IDFGH-1791)

### PR DESCRIPTION
**Pull request by pmeerw**
according IEEE 802.1q

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@pmeerw Thanks for the contribution and sorry for the very slow turnaround. We will look into this PR. Thanks.

**Comment by freakyxue** [comment]
@pmeerw 
this feature has been added in 3.3.
later I wii add in 4.0 .3.3 3.1.
thanks

**Comment by freakyxue** [comment]
fix commit ID :
4f0ee78558f23e4c4305d03d89b8e27710bedf75

**Comment by freakyxue** [comment]
This macro has been cancelled in lwip2.1.2
https://gitlab.espressif.cn:6688/espressif/esp-lwip/commit/d99d91dae97cdc76fdde28e5e3cf04b1c198a27e

**Comment by Alvin1Zhang** [comment]
@pmeerw Thanks for your contribution and sorry that it took so long for this ticket. Will close the PR, thanks for contribution again.

**Pull request closed without merging**
