### PR TITLE
Multi-CDC-ACM Support (IDFGH-6350)

### PR DESCRIPTION
**Pull request by moefear85**
I've modified some of the esp-idf & tinyusb files so that menuconfig exposes options to choose more than 1 USB-CDC-ACM channel. Please merge so everybody can benefit. Please see the patch files in the root folder. It only applies to a handful of files, not all of the files listed below. I'm a git noob.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by tore-espressif** [comment]
Hello @moefear85 ,
Thank you very much in your interest and contribution.

However, we can't accept Pull Requests in form of  `.patch` files; it would have to be a regular git commit. Moreover, there is a lot of commented-out code and other details. Please see our [contributing guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/index.html#before-contributing).
If you want to finish the PR yourself, could you please also change the target branch from `release/v4.3` to `master`? This PR, as is, would pollute our git history.

We are internally working on expanding the CDC-ACM USB device, so we can provide more examples soon.

**Comment by tore-espressif** [comment]
Linking related issue #7020

**Comment by tore-espressif** [comment]
Commit https://github.com/espressif/esp-idf/commit/6330d5d31273bd1c3515ed20515b7cdf64117a08 is doing something very similar but with only 2 channels.

The reason for this limitation is that USB peripheral implementation has only 6 hardware endpoints and one CDC channel needs 3 endpoints. That leaves us with max 2 CDC channels.

**Pull request closed without merging**
