### PR TITLE
Kittinson patch 1

### PR DESCRIPTION
**Pull request by kittinson**

### CODE REVIEW

**Comment by Dazza0** [comment]
Please squash your commits into a single commit and update the commit message to include a short description of the changes made.

**Comment by kittinson** [comment]
I changed colors in css file, in order to make documentation website look like official website.

**Comment by igrr** [comment]
Thanks @kittinson, this is now in the review and merge queue.

**Comment by krzychb** [comment]
Merged in https://github.com/espressif/esp-idf/commit/ae728d66c8808baa475908fbfa68310d0df5eebe. 
This was a great idea to add Espressif touch to documentation template. Thanks @kittinson!

**Pull request closed without merging**
