### PR TITLE
[intr_alloc] Fix missing portEXIT_CRITICAL_SAFE  (IDFGH-8403)

### PR DESCRIPTION
**Pull request by tgotic**
Add missing portEXIT_CRITICAL_SAFE.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by Dazza0 — APPROVED** [review]
@tgotic Thanks for your contribution. The changes LGTM. I'll update the commit message before signing the commit off.

**Comment by KaeLL** [comment]
@Dazza0 doesn't this qualify as a fix which should be backported?

**Comment by Dazza0** [comment]
@KaeLL Yes, this PR will be backported to v5.0 as the bug was introduced in 50a58b4a831745570d5c4d79d6c3dba2f0d6645f

**Pull request closed without merging**
