### PR TITLE
esp_websocket_client: error handling improved and new 'before connect… (IDFGH-7805)

### PR DESCRIPTION
**Pull request by Andste82**
…' event added to improve handling OAuth flows

* error handling is now similar to mqtt client, allowing handling of socket and TLS errors
* handling of http status codes during upgrade handshake is now possible
* new headers setter function added
* added before-connect event to modify URL or headers before websocket re-/connect (similar to mqtt client)

now it is easy to implement OAuth flows and token renewal mechanism in a simple way.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by gabsuren** [comment]
@Andste82 thank you for the contribution, the changes LGTM. 
@euripedesrocha can you please check the transport layer part?

**Comment by gabsuren** [comment]
@Andste82 thank you for the contribution, the changes LGTM.
@euripedesrocha can you please check the transport layer part?

**Comment by gabsuren** [comment]
@Andste82 also one note, web-socket-client library is migrated to [esp-protocols](https://github.com/espressif/esp-protocols). Can you please forward your changes to that repo?

**Comment by Andste82** [comment]
@gabsuren Thanks for your review. I can forward all the web-socket-client changes to the new repo, but I don't actually have an IDF 5.0 project running to test these changes. and indeed the transport layer is not part of the [esp-protocols](https://github.com/espressif/esp-protocols) repo, someone needs to migrate these changes to the IDF 5.0 as well.

**Comment by david-cermak** [comment]
@Andste82 Thanks very much for implementing this useful feature and sharing with us. The IDF changes have been accepted in
9def9b6a03f295b356865a7a4f4b32b7c13c9c0e (on master) and 481cca34904dd052a69fa55a298ce335cf227317 on `v5.0`.
We don't intent to backport it to `v4.4`, as we usually do not backport features. Please reopen if there's a strong need for this change in `v4.4`

**Pull request closed without merging**
