### PR TITLE
log and httpd-performance optimizations (IDFGH-4484)

### PR DESCRIPTION
**Pull request by Jermolinski**
Prevent system assertion at start up in case the log level is set to debug or higher in the configuration file

### CODE REVIEW

**Comment by Jermolinski** [comment]
httpd_sess_* functions have been re-designed to optimize httpd performance

**Comment by Jermolinski** [comment]
Existing httpd_sess_* functions simplified

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by mahavirj** [comment]
@Jermolinski Can you please add some description about changes done in this PR? Also it will be helpful if you can split PR into 2, one for HTTP server change, one for assertion issue.

Please note that, it will be difficult to accept any change where public API is marked as non-supported or moved to private header. Please refactor PR accordingly.

**Comment by Jermolinski** [comment]
=> Can you please add some description about changes done in this PR
1. http_sess* functions have been re-designed to avoid slow searching by fileId during of the all session processing. 
2. There is now only one enum function httpd_sess_enum to enumerate over the existing session slots, which is used in conjunction with a new enum function (EnumFunction) for various tasks (see enum EnumTask)
3. The function httpd_server (in httpd_main) has been updated to use the new enumerate function to process all active session slots as before.  A new function httpd_process_session has been added to process single session slot. This function will be called by the function httpd_sess_enum from httpd_server function.

=>Also it will be helpful if you can split PR into 2, one for HTTP server change, one for assertion issue.
Sorry, I'm not yet familar with git (I've been using svn for the last 12 years :))
I didn't know that several commits will be automatically added to a single pull request.
Is there any description, how developers should proceed to create multiple pull requests to the same master?
Do I have to create a new branch for each pull request?

=>Please note that, it will be difficult to accept any change where public API is marked as non-supported or moved to private header. Please refactor PR accordingly.
I have restored the public function httpd_sess_trigger_close (internally calls new httpd_sess_trigger_close_). 
So there are no changes in the public interface anymore

**Review by shubhamkulkarni97 — CHANGES_REQUESTED** [review]
* Please check the [contribution guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/index.html) for ESP-IDF.
* The assert issue is already fixed in internal repo, it will be synced to GitHub once all internal checks are passed. So, you can remove assert related commit from this PR.
* Please rebase this PR to ESP-IDF master branch and squash all the commits.
* It will be easier to understand if you can add comments regarding changes in the code.

**Comment by Jermolinski** [comment]
ok, I have the rebased my fork to the ESP-IDF master branch 
I have renamed methods, variables, changed brackets as sugested

**Comment by shubhamkulkarni97** [comment]
@Jermolinski This PR contains 14 commits, please squash all of them into a single commit. Reference for squashing the commits: https://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/

**Comment by Jermolinski** [comment]
1. I've squashed all commits to a single one. 
2. The functionality with lru_socket member of sock_db (which I have removed) should be probably verified (whether it is still required or not) by the developer, who had implemented it. I don't see any purpose of marking a session as lowest_lru, because the session with the lowest_lru will be deleted right after it has been found.

**Comment by mahavirj** [comment]
Fixed with https://github.com/espressif/esp-idf/commit/282726b619d6c36ca885a195102ce7ce6ae23649

**Pull request closed without merging**
