### PR TITLE
pppos-client: Refactor modem component (IDFGH-4671)

### PR DESCRIPTION
**Pull request by jonathandreyer**
The idea of this refactoring is to centralize all methods (& handle) which are defined in specifications (GPRS, 3GPP TS 27.007 & V.25TER) in the `esp_modem_dce_service` files (.c & .h). That can remove duplicate lines.

This PR hasn't been tested on all modems, but a similar refactor has been tested on SIM7000. It can be considered a an proposition which needs to be fully reviewed.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by AshUK** [comment]
Can confirm these changes also works on the BG96 and BG95 modems.

I am much in favour of this work towards a generic 3GPP driver. It really would help clean up the driver code and thus make it more reliable.

**Review by david-cermak — APPROVED** [review]
LGTM, thanks for this contribution.

My only (minor) comment was the `DCE_CHECK()` macro in the public includes, but this has been amended internally. This is ready for merging, but may take some time before it gets published on GitHub.

**Comment by jonathandreyer** [comment]
@Alvin1Zhang & @david-cermak I think we can close the issues regarding the commits that you have push. Is it OK for you?

**Comment by Alvin1Zhang** [comment]
@jonathandreyer Thanks for your contribution again, have closed just now.

**Pull request closed without merging**
