### PR TITLE
fix to be BLUFI_TYPE_DATA_SUBTYPE_SOFTAP_CHANNEL. (IDFGH-996)

### PR DESCRIPTION
**Pull request by KAMEDAkyosuke**
BLUFI_TYPE_DATA_SUBTYPE_SOFTAP_MAX_CONN_NUM is duplicate.

I think that BLUFI_TYPE_DATA_SUBTYPE_SOFTAP_CHANNEL is correct in this case.
Because `info->softap_channel` is set.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@KAMEDAkyosuke Thanks for the contribution and sorry for the slow turnaround. We will look into this PR. Thanks.

**Comment by GYC-Espressif** [comment]
Hi, thank you for your contribution. Sorry for reply so late. We have confirmed this issue. Thank you very much for your PR. This PR currently conflicts with the existing IDF file. Can you help resolve this conflict? We will merge your PR. Alternatively, with your consent, we can also merge your solution internally.  Looking forward to your reply.

**Comment by KAMEDAkyosuke** [comment]
@GYC-Espressif Hi. I resolved conflict.

**Comment by KAMEDAkyosuke** [comment]
@GYC-Espressif @jack0c fixed?

https://github.com/espressif/esp-idf/commit/46c53ab8c8b4e1cc94157ff543081ce0ed4b76bc#diff-722f9fc9bb43a0ba41de9525be09ac92

**Comment by Alvin1Zhang** [comment]
Thanks for contribution and sorry for late reply, changes have been merged with https://github.com/espressif/esp-idf/commit/46c53ab8c8b4e1cc94157ff543081ce0ed4b76bc#diff-722f9fc9bb43a0ba41de9525be09ac92. Thanks.

**Pull request closed without merging**
