### PR TITLE
usb_serial_jtag: make CONFIG_DEFAULT initializer match order of structure definition (IDFGH-7218)

### PR DESCRIPTION
**Pull request by davidzuhn**

### CODE REVIEW

**Comment by davidzuhn** [comment]
Without this, compiling with C++ throws an error because the order of initialization does not match the order in the structure definition.   
```
In file included from /Users/zoo/esp32/programs/console-advanced-cplusplus/main/console_example_main.cpp:23:
/Users/zoo/esp32/programs/console-advanced-cplusplus/main/console_example_main.cpp: In function 'void initialize_console()':
/Users/zoo/esp32/esp-idf-fork/components/driver/include/driver/usb_serial_jtag.h:38:1: warning: missing initializer for member 'usb_serial_jtag_driver_config_t::tx_buffer_size' [-Wmissing-field-initializers]
 }
 ^
/Users/zoo/esp32/programs/console-advanced-cplusplus/main/console_example_main.cpp:106:47: note: in expansion of macro 'USB_SERIAL_JTAG_DRIVER_CONFIG_DEFAULT'
     const usb_serial_jtag_driver_config_t cfg=USB_SERIAL_JTAG_DRIVER_CONFIG_DEFAULT();
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/zoo/esp32/esp-idf-fork/components/driver/include/driver/usb_serial_jtag.h:38:1: error: designator order for field 'usb_serial_jtag_driver_config_t::tx_buffer_size' does not match declaration order in 'usb_serial_jtag_driver_config_t'
 }
 ^
```

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by suda-morris** [comment]
sha=9d93aef2b7d49527f2b263df84d5ecbc16822b9f

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, changes merged with https://github.com/espressif/esp-idf/commit/080953ce027e80c7e21ab4c8a295bf0cab98b2ee.

**Pull request closed without merging**
