### PR TITLE
docs: fix spelling errors in bt_spp_initiator (IDFGH-6281)

### PR DESCRIPTION
**Pull request by cvvletter**
when checking the menuconfig, we see that the first option should be 'component config'

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by Dazza0 — APPROVED** [review]
@cvvletter Changes LGTM. Could you squash your commits into a single commit. Thanks.

**Comment by cvvletter** [comment]
@Dazza0 I have squashed them, I believe. The two commits are now one.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again, changes merged with https://github.com/espressif/esp-idf/commit/86d2e09629c8a555284ccf170db53ff69c4340be.

**Pull request closed without merging**
