### PR TITLE
GPIO2 note updated

### PR DESCRIPTION
**Pull request by Pomezny**
Updated note on GPIO2 with informations about possible pull-down resistor and where to find in on DOIT board.

### CODE REVIEW

**Comment by projectgus** [comment]
Hi @Pomezny ,

Thanks for sending this PR.

Warning users to check for GPIO 2 is a really good idea, thanks for adding this.

Unfortunately we can't start add notes/warnings to the docs for specific third party development board designs. These are hard to keep track of, and documentating limitations is the board manufacturer's responsibility. Maybe DOIT has a wiki or something that this info could be put on? Or you could post on esp32.com?

The documentation could say something like "Check the schematic of your development board for anything connected to GPIO 2", though.

**Comment by Pomezny** [comment]
@projectgus I updated file as you advised.

**Comment by projectgus** [comment]
Thanks @Pomezny, looks good!

**Comment by projectgus** [comment]
Cherry-picked in e7693b8. Thanks!

**Pull request closed without merging**
