### PR TITLE
gpio_isr_register(): Correct order of arguments in docs (IDFGH-1780)

### PR DESCRIPTION
**Pull request by thierer**
Make documentation order consistent with function signature.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@thierer Thanks for the contribution. We will look into this PR, thanks.

**Comment by X-Ryl669** [comment]
Is the order important ? 
I thought the documentation tool would find out the param name in the line (just after the `@param` token) and match it with the function signature. At least Doxygen does this.

**Comment by thierer** [comment]
> I thought the documentation tool would find out the param name in the line (just after the @param token) and match it with the function signature. At least Doxygen does this.

[The generated documentation suggests that it does not](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/gpio.html#_CPPv417gpio_isr_registerPFvPvEPviP17gpio_isr_handle_t):

Screenshot 2019-09-05 at 23 22 34

**Comment by igrr** [comment]
Thanks for the PR @thierer, the fix has been cherry-picked as 75e0c6a.

**Pull request closed without merging**
