### PR TITLE
freertos: fix multicore scheduler (IDFGH-5635)

### PR DESCRIPTION
**Pull request by negativekelvin**
This is a quick proposal to fix the issues described below.  Please review as I can't claim this is well thought out or fully tested.

> ToDo: This scheduler doesn't correctly implement the round-robin scheduling as done in the single-core
> 		 *  FreeRTOS stack when multiple tasks have the same priority and are all ready; it just keeps grabbing the
> 		 *  first one. ToDo: fix this.
> 		 *  (Is this still true? if any, there's the issue with one core skipping over the processes for the other
> 		 *  core, potentially not giving the skipped-over processes any time.)

### CODE REVIEW

**Comment by negativekelvin** [comment]
These are the results of a test that creates 5 tasks on each core that share the idle priority and never block, relying only on time-slicing and preemption to share CPU.  

Without patch:

```
Running tasks CPU usage:
 main                   2193789         <1%
IDLE            111006000               39%
test task 1-0   30180030                10%
test task 1-1   28000021                9%
test task 0-0   56530016                20%
test task 0-1   27990017                9%
test task 0-2   27990016                9%
test task 0-3   27990017                9%
test task 0-4   27990017                9%
test task 1-2   139960022               49%
test task 1-3   27990021                9%
test task 1-4   27990021                9%
IDLE            27559788                9%
ipc0            4871            <1%
esp_timer       19              <1%
ipc1            9897            <1%
```

With patch:

```
Running tasks CPU usage:
 main                   6513760         <1%
test task 0-1   135528372               16%
test task 1-1   134210021               16%
test task 1-4   137530021               16%
test task 1-2   134090021               16%
test task 0-2   134181705               16%
test task 1-0   137600029               16%
test task 0-3   135561710               16%
test task 1-3   134180021               16%
test task 1-4   134151800               16%
IDLE            137689790               16%
IDLE            135641756               16%
test task 0-0   133730769               16%
esp_timer       17              <1%
ipc1            9884            <1%
ipc0            4858            <1%
```

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by negativekelvin** [comment]
@zikalino do you want to review this?

**Comment by negativekelvin** [comment]
Note: Freertos smp does a similar thing

https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/fa6982c99ad2a77693f31b7f40a92469dc35753a/tasks.c#L929-L930

**Comment by Dazza0** [comment]
@negativekelvin Thank you for your contribution. The new "Best Effort Round Robin" scheduling in https://github.com/espressif/esp-idf/commit/8babb3bca6f206ea463d125e2e8ab174d94818a0 should now implement these changes.

**Comment by AxelLin** [comment]
@Dazza0 

This PR was created quite long time ago.
I'm surprised you didn't merge it without any comments.
IMHO, this discourages people to contribute.

**Pull request closed without merging**
