### PR TITLE
minor typo fix (IDFGH-6977)

### PR DESCRIPTION
**Pull request by howroyd**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by ESP-Marius — APPROVED** [review]
Thanks for this fix!

**Comment by ESP-Marius** [comment]
sha=07fd196b668b2b3dd7ce31aca46095ebcfaa11c2

**Comment by howroyd** [comment]
You're welcome.  It isn't much (at all!) but hopefully marks the start of me contributing more (useful) stuff in the future!

**Comment by howroyd** [comment]
I am trying to sign the CLA, but am faced with a pretty much blank screen?  Is there supposed to be a UI here? Screenshot:
oyE8OWfIQUKX0NTvgrm1Xw

**Comment by ESP-Marius** [comment]
The fix has already been merged in our internal gitlab repo, this topic should get an automatic update when it's synced to Github

**Pull request merged**
