### PR TITLE
Ringbuffer to iram (IDFGH-7696)

### PR DESCRIPTION
**Pull request by vavroa**
#9198

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by bugadani** [comment]
Is it really necessary to place `prvInitializeNewRingbuffer` into IRAM?

**Comment by ESP-Marius** [comment]
@vavroa Thanks for reporting this.

Seems like the problem might be bigger than just the UART though, as other drivers might also experience similar issues.

So we decided to take a different approach and have an internal MR in-review now where we add separate kconfig option for placing the ringbuffers in flash.

Lets keep this PR open until the fix is merged though, just incase we decide to with your solution instead :)

**Comment by ESP-Marius** [comment]
Resolved by a940064748fcf9da26592516258fe65d2e52aa9a

**Pull request closed without merging**
