### PR TITLE
lwip allow queue size overrides (IDFGH-5246)

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**
Allow overriding TCP_SND_QUEUELEN and TCP_SNDQUEUELOWAT in sdkconfig.

Fixes my issue #7010

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by negativekelvin** [comment]
Add help text and ranges based on lwip docs

**Comment by david-cermak** [comment]
@0xFEEDC0DE64 Would adjusting just the `CONFIG_LWIP_TCP_SND_BUF_DEFAULT` help with your issue? I think keeping these options configurable by users may need some expertise (lwip has some sanity checks, though)

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64 Thanks for your contribution, any further updates regarding @david-cermak 's question? Thanks.

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64 Thanks for your contribution, any further updates regarding @david-cermak 's question? Thanks.

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64 Thanks for your contribution, any updates regarding @david-cermak  comments? Thanks.

**Comment by 0xFEEDC0DE64** [comment]
I did never encounter that issue and I do not need the sizes configurable anymore, are you ok with closing this pull request without merging anything?

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again, will close, thanks.

**Pull request closed without merging**
