### PR TITLE
EspNimbleGattEvent.c (IDFGH-7976)

### PR DESCRIPTION
**Pull request by Alexx-Z**
The NimBLE based Gatt Event solution for ESP32 in ESP IDF environment

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by rahult-github** [comment]
Hi @Alexx-Z , can you please comment as to why the existing blecent / bleprph examples which showcases demo application for gatt client / server usage not enough ?

**Comment by igrr** [comment]
Hi @Alexx-Z,
adding to @rahult-github's question, please note that adding a .c file to the root of the repository is not sufficient to create a new ESP-IDF example project. Please check this section of the contributing guide: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/creating-examples.html if you'd like to create a new example.
That said, if the new example functionality overlaps with one of the existing examples, it might be better to propose concrete improvements to the existing example than to create an entirely new one.
(This applies to the other PRs you have opened, as well.)

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again, will close now and please help refer to https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/index.html.

**Pull request closed without merging**
