### PR TITLE
Use Linux i386/AMD64 binaries on FreeBSD. (IDFGH-5492)

### PR DESCRIPTION
**Pull request by cederom**
FreeBSD can natively emulate Linux ELF binaries.
This commit allows automated Linux tools deployment on FreeBSD.

Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by cederom** [comment]
I can confirm that this commit allows build Zephyr for ESP32 on FreeBSD using Linux toolchain when following instructions provided in the official Zephyr HandBook are met: https://docs.zephyrproject.org/latest/boards/xtensa/esp32/doc/index.html. It is very important to setup environmental variables as instructed :-)

It may be really nice to add `west espressif path` command that would quickly return full path to the xtensa toolchain location on the filesystem (installed with `west espressif install`), so that could be passed to set up the environment scripts before build :-)

If you are the authors of the `west espressif` part please consider such option :-)

**Comment by igrr** [comment]
cc @sylvioalves for `west espressif` part

**Comment by sylvioalves** [comment]
@cederom yes, it was: https://github.com/zephyrproject-rtos/hal_espressif/pull/44

**Comment by cederom** [comment]
System default Python:
```
% python
Python 3.8.12 (default, Sep 11 2021, 01:14:09)
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> PYTHON_PLATFORM = platform.system() + '-' + platform.machine()
>>> print(PYTHON_PLATFORM)
FreeBSD-amd64
```

VEnv Python:
```
% zvenvsdk.sh venv
(venv38zephyr) python
Python 3.8.12 (default, Sep 11 2021, 01:14:09)
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> PYTHON_PLATFORM = platform.system() + '-' + platform.machine()
>>> print(PYTHON_PLATFORM)
FreeBSD-amd64
```

**Comment by cederom** [comment]
Okay, that was problem with my local Zephyr Env launcher script, I have removed and re-created everything from scratch and it works now! :-)

SORRY, and THANK YOU for your time @sylvioalves !! :-)

I can see that this `ESP-IDF` is a core for Zephyr and NuttX. Sweet! :-)

I would like to try ESP32-C3 / RISC-V on both Zephyr and NuttX :-)

Quick question what toolchain env variable should I use for riscv on Zephyr do you know? :-)

**Comment by cederom** [comment]
```
(venv38zephyr) west espressif install
=== downloading ESP-IDF tools..
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, riscv32-esp-elf, openocd-esp32
Skipping xtensa-esp32-elf@esp-2020r3-8.4.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2020r3-8.4.0 (already installed)
Skipping riscv32-esp-elf@1.24.0.123_64eb9ff-8.4.0 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20200709 (already installed)
=== downloading ESP-IDF tools completed
The toolchain has been downloaded to /home/XXX/.espressif/tools/zephyr
Export or set the following variables into the environment:
export ESPRESSIF_TOOLCHAIN_PATH="/home/XXX/.espressif/tools/zephyr"
export ZEPHYR_TOOLCHAIN_VARIANT="espressif"
```

Blinky nor Hello World does not build yet, but I have a good starting point, thank you @sylvioalves ! I will return with success or when Im stuck :-) Thank you!! :-)

**Pull request merged**
