### PR TITLE
Missing SENDER_EMAIL in snprintf (428) (IDFGH-3088)

### PR DESCRIPTION
**Pull request by svenbieg**
I did not try the example, but snprintf should crash!

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@svenbieg Thanks for noting this and the contribution, we will look into. Thanks.

**Comment by vikramdattu** [comment]
@svenbieg The example already uses "ESP32 SMTP Client" as Sender.

Not needed to add actual email address in header. MAIL FROM already takes care of that.

**Comment by svenbieg** [comment]
Yes, i know. The point is that the snprintf-function expects two string-parameters and only one is provided. The function will print whatever is on the stack. The program compiles but because variable arguments are not checked.

**Comment by svenbieg** [comment]
I could successfully send an e-mail with this example via web.de, but i had to send another EHLO after the TLS-handshake. The line-endings are inconsistent too. I'm always using \r\n, and \r\n twice after the header.

**Comment by vikramdattu** [comment]
@svenbieg 

```
    len = snprintf((char *) buf, BUF_SIZE,
                   "From: %s\r\nSubject: mbed TLS Test mail\r\n"
                   "To: %s\r\n"
                   "MIME-Version: 1.0 (mime-construct 1.9)\n",
                   "ESP32 SMTP Client", RECIPIENT_MAIL);
```

**Comment by vikramdattu** [comment]
> I had to send another EHLO after the TLS-handshake.

This looks like some server specific behaviour to me.

> The line-endings are inconsistent too. I'm always using \r\n, and \r\n twice after the header.

Please let us know where you faced this issue. Please send an MR for this if you wish to.

**Comment by svenbieg** [comment]
I'm sorry, i didn't see the comma between the strings.

**Pull request closed without merging**
