### PR TITLE
Return EAGAIN in http client perform (IDFGH-6997)

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**
I needed to get the two separate response bodies on a web resource with basic authentication.

First request always fails with [401 Unauthorized](https://developer.mozilla.org/de/docs/Web/HTTP/Status/401) and contains some response body.

Second request succeeds as the needed Authentication header is sent with.

I need both request bodies and by returning EAGAIN i can read both bodies separately. Does this have anything to do with is_async config?

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by KaeLL — COMMENTED** [review]
Why keep the commented code?

**Comment by 0xFEEDC0DE64** [comment]
> 

I expect lots of discussions happening and that this wont be the final version.

Maybe idf users are not expecting EAGAIN yet and dont call again, which would break existing http requests with auth

**Review by Dhananjay-JSR — APPROVED** [review]

**Comment by 0xFEEDC0DE64** [comment]
@Dhananjay-JSR can you approve again?

**Comment by shubhamkulkarni97** [comment]
Hi @0xFEEDC0DE64, sorry for delayed response.

Did you consider using event handler for this purpose?

`HTTP_EVENT_ON_DATA` and `HTTP_EVENT_ON_FINISH` is generated for both the requests. You can use event handler to read body for first request and set headers for second request.

Please refer to the event handler in esp_http_client example: https://github.com/espressif/esp-idf/blob/4350e6fef859b94f3efae6ceced751911c9d2cbc/examples/protocols/esp_http_client/main/esp_http_client_example.c#L46-L119

Hope this fixes your issue!

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, will close due to short of feedback, feel free to reopen with more updates.

**Pull request closed without merging**
