### PR TITLE
component path relative to IDF (IDFGH-9429)

### PR DESCRIPTION
**Pull request by ldab**
Change the component path to relative to the IDF as the build will fail if the example is moved from its folder.

### CODE REVIEW

**Comment by igrr** [comment]
Thanks for the PR @ldab! We accept pull requests on `master` branch only, to ensure that one the issue is fixed, it is fixed for all subsequent versions. Once it is merged to `master`, we can backport the fix to the release branches.
Could you please rebase this PR and change the target branch to `master`?

**Comment by rahult-github** [comment]
sha=4c2afac35502161ce473660c99e17feb013a378d

**Comment by rahult-github** [comment]
sha=c88efb7fa8fdd469dbd1a1814d0500239f82e85c

**Comment by Alvin1Zhang** [comment]
Thanks for contribution again, changes have been merged with https://github.com/espressif/esp-idf/commit/60a7fe99f7f31897dceb3c54837629099b762099.

**Pull request closed without merging**
