### PR TITLE
fixed debug spi args (IDFGH-4161)

### PR DESCRIPTION
**Pull request by sdrabb**
Fixed debug slave arguments

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by Icarus113** [comment]
Thanks for following up. But we don't need this debug code any more, it'll be removed.

**Comment by sdrabb** [comment]
> Thanks for your contribution.

It's a pleasure

**Comment by sdrabb** [comment]
> Thanks for following up. But we don't need this debug code any more, it'll be removed.

You're welcome... I think it still useful during SPI debugging

**Pull request closed without merging**
