### PR TITLE
pthread: avoid heap alloc in pthread_cond_timedwait if possible (IDFGH-7409)

### PR DESCRIPTION
**Pull request by MacDue**
This creates the wait sem with `xSemaphoreCreateCountingStatic` if possible taking around 80 bytes off the stack.
This semaphore is only used for the life of this function, which can be quite heavily called, so this avoids any possible heap/performance issues.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by igrr — CHANGES_REQUESTED** [review]
This looks like a useful improvement, thank you! Have left one minor comment.

By the way, have you done any benchmarks to see how much this change improves performance?

**Comment by MacDue** [comment]
I don't think this changes the runtime performance really (since you normally will be waiting at least a few milliseconds in the cond_timedwait). 

My main thought with this change was to avoid the possibility of heap fragmentation when waiting for longer timeouts, 
though I've not got anything quantifiable for that (it was just something I thought about when looking over the code due to an unrelated issue).

**Comment by 0xjakob** [comment]
sha=c104662192c35ddc01050310ec96705894a75889

**Comment by 0xjakob** [comment]
@MacDue Your code is [available on master ](https://github.com/espressif/esp-idf/commit/253b952f4db8768b0b123037cd1c1e050b8e66c0) already. Because it is merged already, we are closing this PR.

**Pull request closed without merging**
