### PR TITLE
for Wi-Fi initialization without esp_wifi_init but enabled power management (IDFGH-2092)

### PR DESCRIPTION
**Pull request by Rojer-x86**
for Wi-Fi initialization without esp_wifi_init but enabled power management

### CODE REVIEW

**Comment by igrr** [comment]
Hi @Rojer-x86, can you add a bit more context, when is this new function required?

**Comment by Rojer-x86** [comment]
> Hi @Rojer-x86, can you add a bit more context, when is this new function required?
if i want wifi initialization without default event handlers. function esp_wifi_init set default event handlers, but if initialization over esp_wifi_init_internal with enabled power management then pm lock don't create and any try acquire/releas leads to an error

**Comment by igrr** [comment]
Thanks, understood.

There is a change to the tcpip_adapter coming soon, which will make it possible to bypass the event handlers registration in a nice way. Will update you when this change is merged.

**Comment by igrr** [comment]
Another option is to remove the event handlers, as shown in this example: https://github.com/espressif/esp-idf/blob/758db1e008d4a524b4f386367760b6259e6d6737/examples/ethernet/eth2ap/main/ethernet_example_main.c#L195

**Comment by Rojer-x86** [comment]
this function exists only in version 4.0 in 3.3 lts I didn't find

**Comment by zhangyanjiaoesp** [comment]
@Rojer-x86 Does you problem still exist?

**Comment by jack0c** [comment]
I will close this issue since release/v3.3 got EOL.

**Pull request closed without merging**
