### PR TITLE
Fix init of esp_bt_controller_config_t (IDFGH-11156)

### PR DESCRIPTION
**Pull request by HeMan**
Should fix compilation errors like https://github.com/esphome/issues/issues/4909

### CODE REVIEW

**Comment by krzkraw** [comment]
I just encountered this issue while wanting to set up bluetooth proxy, ESPHome with latest release of ESP-IDF on ESP32-C6

**Comment by bmidi** [comment]
Was this merged? Looks like this could be fixed as well: https://github.com/esphome/issues/issues/4909#issuecomment-1820479345

**Comment by freddiebd** [comment]
Has this been merged now?

**Comment by zhaoweiliang2021** [comment]
The commit 7eb1a29eb8207bcbb1ca8be8f6c0b484c32b5ecb in master branch fixed this issue, thanks

**Comment by HeMan** [comment]
Should I close this PR then?

**Comment by weiyuhannnn** [comment]
@HeMan  Thanks for your contribution. The fix has been committed, and I will close this PR.

**Pull request closed without merging**
