### PR TITLE
fix: corrected typo from disbale to disable in numerous places (IDFGH-11298)

### PR DESCRIPTION
**Pull request by DevinNorgarb**
Just a few corrections of the typo `disbale` to `disable`

Thanks for your consideration

### CODE REVIEW

**Comment by DevinNorgarb** [comment]
Hi @zhp0406, the build steps say the build is failing due to not having committed using the pre-commit tool. 
However, I installed and ensured my commits complied with the pre-commit rules before pushing. 
Is there any further action required from my side? 
Thanks in advance. 
image
****

**Comment by zhp0406** [comment]
@DevinNorgarb 
I will help you through the pipeline and submit your code.

**Comment by DevinNorgarb** [comment]
@zhp0406 Thank you! 
If there is anything further you need from me please let me know.

**Comment by zhp0406** [comment]
@DevinNorgarb 
Thank you for your fix, now the commit（001b10ec4592881419b5672de5329add13618a48） is visible. If there are no other issues, this issue can be closed.

**Pull request closed without merging**
