### PR TITLE
esp_event: Fix misuse of recursive semaphore take/give calls for prof… (IDFGH-4246)

### PR DESCRIPTION
**Pull request by AxelLin**
…iling_mutex

The profiling_mutex is created by xSemaphoreCreateMutex(), so don't use the
recursive version of semaphore take/give calls.

Signed-off-by: Axel Lin <axel.lin@gmail.com>

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by AxelLin** [comment]
@mahavirj 
Any chance to review this trivial fix?

**Comment by mahavirj** [comment]
> Any chance to review this trivial fix?

Change looks good to me. But I can see similar change in our internal code-base (yet to sync with github though), so we are good for now :-)

**Comment by AxelLin** [comment]
> > Any chance to review this trivial fix?
> 
> Change looks good to me. But I can see similar change in our internal code-base (yet to sync with github though), so we are good for now :-)

It's actually not a similar change but exactly the *same* fix.
So you guys didn't pull the PR but apply and commit the fix manually.
It's simply wrong way to handle PR.

**Comment by lhespress** [comment]
@AxelLin sorry for we re-created your commit so the information is missing. we’ll pay attention next time.

**Pull request closed without merging**
