### PR TITLE
Fix string on encrypting failure (IDFGH-6905)

### PR DESCRIPTION
**Pull request by KonssnoK**
as per title

### CODE REVIEW

**Review by mrengineer7777 — APPROVED** [review]
Nice catch on debug message

**Comment by KonssnoK** [comment]
yeah easy to spot it when you make your own application crash and try to understand why 🙃

**Comment by igrr** [comment]
Hi @KonssnoK, thank you for the PR! We accept contributions on `master` branch only. Could you please rebase your PR on top of `master` and change the base branch? Once the PR is merged we can backport the fix to release/v4.4 as well.

**Comment by KonssnoK** [comment]
Well I made a new one... Sorry, first time :D

**Pull request closed without merging**
