### PR TITLE
Getting started: Fix VS Code extension setup link (IDFGH-4840)

### PR DESCRIPTION
**Pull request by bugadani**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for contribution.

**Comment by bugadani** [comment]
@Alvin1Zhang do I need to do something to move this forward?

**Review by brianignacio5 — APPROVED** [review]
LGTM

**Comment by Alvin1Zhang** [comment]
@bugadani Thanks for your contribution, and sorry for late reply, we have put the changes into our internal review queue, and the PR will be updated once the changes are available on GitHub. Thanks.

**Comment by igrr** [comment]
Thanks again for your PR @bugadani! We ended up making a few more changes, they have been done in https://github.com/espressif/esp-idf/commit/b630c45d91c63d628a3b2bc8926e43ed603bdb34. The changes will also be backported to the release branches.

**Pull request closed without merging**
