### PR TITLE
Update uart_events_example_main.c (IDFGH-7532)

### PR DESCRIPTION
**Pull request by ajit1433**
Spelling correction

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by suda-morris** [comment]
sha=08a5b75735f9bfac9611ae77cd22e9f462281d2e

**Comment by o-marshmallow** [comment]
sha=08a5b75735f9bfac9611ae77cd22e9f462281d2e

**Comment by o-marshmallow** [comment]
sha=08a5b75735f9bfac9611ae77cd22e9f462281d2e

**Comment by mahavirj** [comment]
Merged with https://github.com/espressif/esp-idf/commit/39e0d72c053f6177f5612d9a58ff27bd720f4b96

**Pull request closed without merging**
