### PR TITLE
Example spelling fixes

### PR DESCRIPTION
**Pull request by chmorgan**

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks for sending this, @chmorgan .

Can you squash these two commits into one, please? You can find a description of this process here:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/

Thanks,

Angus

**Comment by chmorgan** [comment]
@projectgus squashed and re-pushed for review.

**Comment by projectgus** [comment]
Thanks, have cherry-picked for merging.

**Comment by projectgus** [comment]
Cherry-picked as 76db44e.

**Pull request closed without merging**
