### PR TITLE
lan8740 and lan8742 error fix v4.1 (IDFGH-5345)

### PR DESCRIPTION
**Pull request by AtleHUndrum**
Have implemented a working prototype with esp32-wroom-32e and phy lan8740 with this fix

### CODE REVIEW

**Comment by AtleHUndrum** [comment]
Hi @kostaond can you get this fix to other relases as well for example (4.3) and coordinate wtih PR #7269 ?

**Comment by AtleHUndrum** [comment]
Thanks @kostaond. And let me me know if you backport it.

**Comment by kostaond** [comment]
@AtleHUndrum I internally consulted and we usually backport bugfixes, not new features. This update is considered as feature addition since it extends currently supported chips. Therefore I tend to not backport. I hope you understand our position.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution, changes have been merged with https://github.com/espressif/esp-idf/commit/404905d5f117ce58badb5ebb56b01ff6384ec744.

**Pull request closed without merging**
