### PR TITLE
Fix uart_wait_tx_done hanging forever (IDFGH-3139) (IDFGH-4571)

### PR DESCRIPTION
**Pull request by JosuGZ**
Fixes https://github.com/espressif/esp-idf/issues/5156.

### CODE REVIEW

**Comment by JosuGZ** [comment]
I have also fixed it for v3.2, where the code is different (but the changes are similar), I'm not sure whether submit another PR for that one.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by acf-bwl** [comment]
Would it be possible to have this merged soon? This bug is affecting us as well @Alvin1Zhang et al

Thanks!

**Comment by JosuGZ** [comment]
I think there is an attempt to fix this [here](https://github.com/espressif/esp-idf/commit/c801b3a18209ae707d3f8224b0734315cdc99db8) although it seems wrong (I haven't looked at it deeply, though).

**Comment by AxelLin** [comment]
> I think there is an attempt to fix this [here](https://github.com/espressif/esp-idf/commit/c801b3a18209ae707d3f8224b0734315cdc99db8) although it seems wrong (I haven't looked at it deeply, though).
> 
> You can see [here](https://github.com/espressif/esp-idf/issues/5156#issuecomment-757979976) if it is still reproducible.

Add @alisitsyn

**Comment by ginkgm** [comment]
Hi @JosuGZ , @acf-bwl , @AxelLin 

Let's discuss this here. https://github.com/espressif/esp-idf/issues/5156

**Comment by ginkgm** [comment]
Thanks @JosuGZ . Fix for the same issue merged here: 

https://github.com/espressif/esp-idf/commit/c801b3a18209ae707d3f8224b0734315cdc99db8

https://github.com/espressif/esp-idf/issues/5156

**Pull request closed without merging**
