### PR TITLE
change logs of http ota component (IDFGH-5653)

### PR DESCRIPTION
**Pull request by hiproz**
1. add paired log for line393; 2. change log level to debug

### CODE REVIEW

**Comment by shubhamkulkarni97** [comment]
Hi @hiproz, Thanks for your contribution.

The `Connection closed` logs are checked in the internal test framework. So we cannot change its log level to debug.

**Comment by hiproz** [comment]
ok, i see it.  thanks for the reply

**Comment by hiproz** [comment]
ok, i see it.  thanks for the reply

**Comment by shubhamkulkarni97** [comment]
Hi @hiproz, we have accepted your change. This PR will be linked once the commit is available on GitHub.

Thanks for your contribution!

**Pull request closed without merging**
