### PR TITLE
Fix "error code" Typo (IDFGH-11162)

### PR DESCRIPTION
**Pull request by nkaaf**
Fixed typo: "erro code" -> "error code"

### CODE REVIEW

**Comment by mahavirj** [comment]
sha=51e6d228b446a083d35b5b8e6ece1b9b7c127b10

**Review by mahavirj — APPROVED** [review]

**Comment by jack0c** [comment]
merged to master： f67aa66067c348d483e9c49f8b544af35a46ebfe

**Comment by nkaaf** [comment]
Is there anything I can improve/fix, or why is the PR closed? :)

**Comment by igrr** [comment]
Thanks for your PR @nkaaf, your commit was merged in https://github.com/espressif/esp-idf/commit/2d6dcee1365992a7d48d2fd9ff75b6ed58a4a1ea (the link to the commit is right above). We sometimes have to rebase Github PRs before merging them into the `master` branch, and in this case Github doesn't associate the commit with the PR and doesn't mark the PR is "merged", even though effectively it is. The rebased commit still has you as the author, your contribution is very much appreciated!

**Comment by nkaaf** [comment]
I understand, perfect. :)

**Comment by nkaaf** [comment]
I understand, perfect. :)

**Pull request closed without merging**
