### PR TITLE
Feature : pthread_cancel() (IDFGH-8242)

### PR DESCRIPTION
**Pull request by kewelspintly**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by 0xjakob** [comment]
@kewelspintly We'll take a look at this PR and come back to you afterwards.

**Comment by zikalino** [comment]
@kewelspintly could you sign CLA and also rebase this PR to master?

**Comment by 0xjakob** [comment]
@kewelspintly We're closing this issue since the CLA has not been signed. Additionally, there are cancellation handlers and other POSIX-defined aspects which need to be considered, or else the cancelled thread might, e.g., leave a locked mutex or create other synchronization problems. We might consider adding this API in the future, albeit not having concrete plans at this moment.

If you change your mind and still plan to work on this PR, please feel free to re-open this issue.

**Pull request closed without merging**
