### PR TITLE
esp_mqtt: add option to configure mqtt task priority. (IDFGH-2902)

### PR DESCRIPTION
**Pull request by rezatoune**

### CODE REVIEW

**Comment by rezatoune** [comment]
This adds a Kconfig entry to allow configuring the mqqt task priority.
Related PR for esp_mqtt is at [https://github.com/espressif/esp-mqtt/pull/154](https://github.com/espressif/esp-mqtt/pull/154)

**Comment by Alvin1Zhang** [comment]
@rezatoune Thanks for your contribution.

**Comment by david-cermak** [comment]
@rezatoune Thanks again for posting this change. Makes sense and LGTM. Taken for internal round of review and testing.

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Pull request closed without merging**
