### PR TITLE
fix: S3: configure external oscillator correctly (IDFGH-13553)

### PR DESCRIPTION
**Pull request by 2opremio**
Addresses part of https://github.com/espressif/esp-idf/issues/10269

### CODE REVIEW

**Comment by songruo** [comment]
@2opremio We have fixed the issue in b9c58c550c42f9a8f3efd821a9da49101637b682. Please check if you can use external oscillator on current master now. I will close the PR, if it is still a problem, feel free to reopen or create a new issue.

**Comment by 2opremio** [comment]
The PR doesn’t seem to set the right buf value for the external oscillator.

**Comment by dvosully** [comment]
@songruo b9c58c5 does not fix the external oscillator problem for ESP32-S3. I am using IDF v5.3 which includes that patch. When I apply the above patch from 2opremio instead the external oscillator works.

I am using a custom board, with the 32.768kHz output from a DS3231 RTC capacitively coupled to GPIO15 of an ESP32-S3-WROOM module. The Vpk-pk is 640mV, Vrms is 304mV, square wave, 26% duty cycle. As above, it works when using the patch from 2opremio so a hardware issue seems unlikely.

**Comment by AndreoBotelho** [comment]
> @songruo [b9c58c5](https://github.com/espressif/esp-idf/commit/b9c58c550c42f9a8f3efd821a9da49101637b682) does not fix the external oscillator problem for ESP32-S3. I am using IDF v5.3 which includes that patch. When I apply the above patch from 2opremio instead the external oscillator works.
> 
> I am using a custom board, with the 32.768kHz output from a DS3231 RTC capacitively coupled to GPIO15 of an ESP32-S3-WROOM module. The Vpk-pk is 640mV, Vrms is 304mV, square wave, 26% duty cycle. As above, it works when using the patch from 2opremio so a hardware issue seems unlikely.

Confirmed the same issue with ESP32-C3, the reference manual says that at reset RTC_CNTL_DBUF_XTAL_32K bit is set to ZERO but reading the register at runtime this bit was set to ONE even with external clock configuration, this leads to lots of  error on oscilator startup and calibration, aplying the path from @2opremio solves the issues and the RTC_CNTL_DBUF_XTAL_32K  is correctly set ZERO at runtime, I'm testing on idf 5.5.2

**Pull request closed without merging**
