### PR TITLE
libcoap_430: Update code for use with libcoap 4.3.0 (IDFGH-5355)

### PR DESCRIPTION
**Pull request by mrdeep1**
Add in multicast support for coap_server/coap_client.

Update libcoap logging to use esp-idf logging

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by AdityaHPatwardhan** [comment]
Hi @mrdeep1, Thank you for the PR, I have tested it and works fine. I have raised an internal MR for this and in the process of review and merge.
I just had one doubt.
When we run the `coap_client` example with `coap_server` on other esp32. It gives error `E (8682) CoAP_client: select timeout` after receiving the `Hello World` Message from the server.
Previously, it did not print the Error message.
Is this the expected behaviour ?, can we do something to avoid the error message, as having error message, in example would be confusing for the user !

**Comment by mrdeep1** [comment]
@AdityaHPatwardhan Sure - will look into why we are now getting this message and make it 'a bit less painful'.  I see that
coaps://californium.eclipse.org has been replaced by coaps://californium.eclipseprojects.io recently and will update that as well.

**Comment by mrdeep1** [comment]
@AdityaHPatwardhan I found the issue `E (8682) CoAP_client: select timeout` and fixed it, and re-organized some code in the example to make it more readable.  I have also updated the example code to refer to `coaps://californium.eclipseprojects.io`.

**Comment by AdityaHPatwardhan** [comment]
@mrdeep1 , Thank you for fixing it, I will let you know once it is merged internally, Then it may take a couple of days to be available publicly.

**Comment by mrdeep1** [comment]
@AdityaHPatwardhan I have just updated the certificates so that the client can do `PKI `against `coaps://californium.eclipseprojects.io`

**Comment by mrdeep1** [comment]
Just bumped libcoap library to be released 4.3.0 rather than 4.3.0rc3 - minor docs change and unused compiler disable option fix.

**Comment by AdityaHPatwardhan** [comment]
@mrdeep1 sorry for the late reply, actually these new changes increase the heap usage by around 10KB so this PR was stuck in the review stage. I will investigate it this week that the increased heap was due to libcoap itself or because of removing certain menuconfig options from `port/coap_mbedtls.c`  when this PR moves it to `src/port_mbedtls.c` If it is such case then I am afraid we might have to fall back to some similar structure to `port/coap_mbedtls.c` for decreasing heap usage.

I understand this PR also fixes the issue https://github.com/espressif/esp-idf/issues/7219 so If that's okay with you, I was going take only that part of the commit in your name and open a different MR to fix that issue first and then move to this MR .
Sorry for the delay

**Comment by mrdeep1** [comment]
@AdityaHPatwardhan Sure, replacing `coaps://californium.eclipse.org` with `coaps://californium.eclipseprojects.io` in coap_client example in various places is a good fix for #7219.  If you are going to update the PKI keys (which work for `coaps://californium.eclipseprojects.io`) , then you will need to update coap_server's certs as well.

There has been some minor enhancements to `coap_mbedtls.c`, but I tried to keep the conditional compliations in step, but are now using the Mbed TLS conditional names to make it more generic for other libcoap users - e.g., `CONFIG_MBEDTLS_SSL_PROTO_DTLS` -> `MBEDTLS_SSL_PROTO_DTLS `which esp-idf does under the hood anyway.  It is possible that something may have been missed here, but unlikely (there has been overall a ~900 increase).

What is more likely is the change in libcoap for supporting block-wise transfers (RFC7959) has been moved from being handled by the application down into libcoap so making transparent large data handling a lot easier.  There have been a couple of other updates which will cause code increases such as more rigorous packet checking, proxy support, cache keys and async support.

Some testing shows (building coap_server with no configuration changes)
````
Previous libcoap

            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        236  12315       0      0        0      41848    13521   67920

Without Mbed TLS
            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        228   9007       0      0        0      35823    11925   56983

coap_log() disabled
            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        232   9871       0      0        0      35451     5784   51338

New libcoap

            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        244  12590       0      0        0      63766    17443   94043

Without TCP Enabled
            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        244  12590       0      0        0      58739    15869   87442

Without Mbed TLS
            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        244  10978       0      0        0      55952    15011   82185

coap_log() disabled
            Archive File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total
               libcoap.a        244  10146       0      0        0      55161     7021   72572
````
So the Mbed TLS support has grown from 10937 to 11858.  No-oping coap_log() unsurprisingly gets rid of a lot the usage. differences.

**Comment by mrdeep1** [comment]
Further libcoap file usage research shows (need to think about space reduction possibilities)
````
             Object File DRAM .data & .bss & other   IRAM   D/IRAM Flash code & rodata   Total

             address.c.o          0      0       0      0        0        259       62     321 Old
             address.c.o          0      0       0      0        0        288       87     375 New

               async.c.o          0      0       0      0        0        593      216     809 New

               block.c.o          0      0       0      0        0       1253      301    1554 Old
               block.c.o          0      8       0      0        0       9380     1594   10982 New

          coap_cache.c.o          0      0       0      0        0        577      131     708 New

          coap_debug.c.o         16   5243       0      0        0       2921     2164   10344 Old
          coap_debug.c.o          8   5254       0      0        0       3251     2370   10883 New

        coap_hashkey.c.o          0      0       0      0        0         76        0      76 Old
        coap_hashkey.c.o          0      0       0      0        0          0        0       0 New

             coap_io.c.o          4    280       0      0        0       5745     1933    7962 Old
             coap_io.c.o          0    280       0      0        0       4793      767    5840 New

        coap_mbedtls.c.o          8   3308       0      0        0       5766     1604   10686 Old
        coap_mbedtls.c.o          0   1612       0      0        0       7267     2351   11230 New

           coap_prng.c.o          4      0       0      0        0         82        0      86 New

        coap_session.c.o          0    384       0      0        0       4264     1381    6029 Old
        coap_session.c.o          0    260       0      0        0       7936     1652    9848 New

            coap_tcp.c.o          0      0       0      0        0       1432     1114    2546 New

           coap_time.c.o          0      8       0      0        0        212        0     220 Old
           coap_time.c.o          0      8       0      0        0        277        0     285 New

              encode.c.o          0      0       0      0        0        177       74     251 Old
              encode.c.o          0      0       0      0        0        337       96     433 New

                 mem.c.o          0      0       0      0        0        139      136     275 Old
                 mem.c.o          0      0       0      0        0        139      136     275 New

                 net.c.o          8   3092       0      0        0       9144     2398   14642 Old
                 net.c.o          0   3092       0      0        0      10752     2799   16643 New

              option.c.o          0      0       0      0        0       1975      571    2546 Old
              option.c.o          0      0       0      0        0       2018      571    2589 New

                 pdu.c.o        192      0       0      0        0       2945     1997    5134 Old
                 pdu.c.o        224   2056       0      0        0       6329     2479   11088 New

            resource.c.o          8      0       0      0        0       5279      910    6197 Old
            resource.c.o          8      0       0      0        0       5619     1002    6629 New

                 str.c.o          0      0       0      0        0        124       25     149 Old
                 str.c.o          0     20       0      0        0        295      101     416 New

           subscribe.c.o          0      0       0      0        0         48       67     115 Old
           subscribe.c.o          0      0       0      0        0         48       67     115 New

                 uri.c.o          0      0       0      0        0       1638       34    1672 Old
                 uri.c.o          0      0       0      0        0       2448       46    2494 New
````

**Comment by mahavirj** [comment]
Merged with https://github.com/espressif/esp-idf/commit/ed3d44042878b15779ce586fbb78ffe560fa2399. Thanks for your contribution @mrdeep1

**Pull request closed without merging**
