### PR TITLE
[Usb Serial JTAG] printing to console could sometimes skip bytes (IDFGH-10069)

### PR DESCRIPTION
**Pull request by chipweinberger**
See: https://github.com/espressif/esp-idf/issues/11192 and https://github.com/espressif/esp-idf/issues/9318

### CODE REVIEW

**Comment by ESP-Marius** [comment]
CC @mythbuster5

**Comment by chipweinberger** [comment]
i'll fix the precommit failing

**Comment by chipweinberger** [comment]
fixed.

**Comment by mythbuster5** [comment]
sha=054eacae23c994fa90e8473aea507600ac2bae99

**Comment by chipweinberger** [comment]
@mythbuster5 just want to let you know I took this diff directly from the issue I linked.

It has not been tested by me.

**Comment by mythbuster5** [comment]
I see, I will take a look into this.

**Comment by suda-morris** [comment]
sha=054eacae23c994fa90e8473aea507600ac2bae99

**Pull request closed without merging**
