### PR TITLE
Docs: Use images instead of emojis in the support table of the README

### PR DESCRIPTION
**Pull request by dobairoland**

### CODE REVIEW

**Comment by igrr** [comment]
The images look a bit cropped (Chrome, macOS):

Screenshot 2021-08-31 at 12 24 11

**Comment by dobairoland** [comment]
@radimkarnis I don't see an exception as before but the internal task hasn't been created. Could you please check it?

**Comment by radimkarnis** [comment]
@dobairoland thank you for checking this. PRs from collaborators are not synced by default. See https://github.com/espressif/github-actions/commit/fa06c1b2c2a00567f4f290b852e6b248b1536020

**Comment by dobairoland** [comment]
Thanks @radimkarnis. I missed that point.

**Review by igrr — APPROVED** [review]

**Pull request closed without merging**
