### PR TITLE
fix gpio interrupts lost (IDFGH-5069)

### PR DESCRIPTION
**Pull request by toybox01**
fix race condition

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by toybox01** [comment]
Is this PR under consideration?

**Comment by ginkgm** [comment]
Hi @toybox01 

I think you are right about the interrupt may be accidently cleared without being properly handled. It's really a bug.

But clearing the interrupt before the handler is called is also a breaking change, we are still thinking about how to deal with it properly...

**Comment by tommy1394** [comment]
Hi @toybox01,
I am new to ESP32, and have just discovered this issue in my application.  Is there a way to apply this patch to the Arduino IDE or do I need to move my code to the ESP-IDF?

**Pull request closed without merging**
