### PR TITLE
Change default PoP argument of esp_prov.get_security from None to string (IDFGH-5381)

### PR DESCRIPTION
**Pull request by alexhenrie**
Closes [IDFGH-5380](https://github.com/espressif/esp-idf/issues/7129)

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by shivani-tipnis** [comment]
Hi @alexhenrie

The esp_prov.py provides the option whether you want to use PoP or not as a CLI argument.

Could you tell us your usecase for calling the function separately from a different script ?

Thanks

**Comment by alexhenrie** [comment]
My biggest reason for importing functions from esp_prov.py, but not running esp_prov.py directly, is to send data to a series of custom endpoints, none of which is named "custom-data". It's clear that esp_prov.py was designed to allow importing its functions into other scripts because its main logic is disabled by the `if __name__ == '__main__':` statement when importing.

**Comment by shivani-tipnis** [comment]
Thank you.

**Comment by mahavirj** [comment]
Fixed with https://github.com/espressif/esp-idf/commit/5ed53c272b2fac5c052d2d097b2fd6e9957ffd01, thank you for your contribution.

**Comment by alexhenrie** [comment]
Thank you!

**Pull request closed without merging**
