### PR TITLE
Update rtc_io_periph.h (IDFGH-4374)

### PR DESCRIPTION
**Pull request by Stefano-Orsolini**
solves undefined GPIO_PIN_COUNT error when compiling ulp component.

### CODE REVIEW

**Comment by Stefano-Orsolini** [comment]
also components/soc/esp32/rtc_io_periph.c line 85 needs same:
const rtc_gpio_desc_t rtc_gpio_desc[SOC_GPIO_PIN_COUNT]

using: ESP-IDF v4.3-dev-1901-g178b122-dirty

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by istokm** [comment]
Duplicate of #6029, which still hasn't been merged in nearly 2 months.
I also found this, and fixed it a while back, but realized the duplicate... #6131

**Comment by Stefano-Orsolini** [comment]
thanks, didn't see that!
I'm closing this one

**Pull request closed without merging**
