### PR TITLE
Replaced void* with proper typed netif * (IDFGH-5423)

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by david-cermak — CHANGES_REQUESTED** [review]
One of the primary purpose of `esp_netif` is to decouple the IDF code from network stacks. This change would require users to pre-include lwip headers. This is currently enabled by default:
```
CONFIG_ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER=y
```

So the `netif_impl` pointer at this point should be something more universal, e.g. the opaque `void*` ptr as is, but perhaps it could be a `struct netif *`, but we would have to forward declare the `struct netif` if the lwip is not included.

**Comment by david-cermak** [comment]
@0xFEEDC0DE64 Any idea how to use strong typing and be independent from the lwip at the same time?
We will close this PR if not, thanks.

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64 Thanks for your contribution, any updates regarding @david-cermak 's comments? Thanks.

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64 Thanks for your contribution, any updates regarding @david-cermak comments? Thanks.

**Comment by Alvin1Zhang** [comment]
@0xFEEDC0DE64 Thanks for your contribution again, will close due to short of feedback, feel free to reopen.

**Pull request closed without merging**
