### PR TITLE
 BTM_CheckAdvData will return early because length =0 is encountered (IDFGH-5673)

### PR DESCRIPTION
**Pull request by FaeSorceress**
When adv_data has invalid data 0 and the device name is placed in scan_rsp_data, BTM_CheckAdvData will return early because length =0 is encountered.
I just added a loop to the BTM_CheckAdvData fuction to prevent it from returning early.
But because of the formatting of the editor,it looks a lot difference.I'm so sorry fot it.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by xiewenxiang** [comment]
Hi @FaeSorceress

 Is there something wrong here? Why are there so many unrelated changes.

**Comment by FaeSorceress** [comment]
I just added a loop to the BTM_CheckAdvData fuction to prevent it from returning early，this motification corresponding to issue IDFGH-5671.But because of the formatting of the editor,it looks a lot difference.I'm so sorry about this.


---------------------------------------------------
深圳市启明云端科技有限公司
研发部 软件组
彭飞 18035864063
***@***.*** 
 
From: xiewenxiang
Date: 2021-08-11 09:58
To: espressif/esp-idf
CC: stephen; Mention
Subject: Re: [espressif/esp-idf] BTM_CheckAdvData will return early because length =0 is encountered (IDFGH-5673) (#7394)
Hi @FaeSorceress
Is there something wrong here? Why are there so many unrelated changes.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhp0406** [comment]
Now we have handled the case of zero-length for adv scan rsp, etc. Thank you for submitting the code.

**Comment by zhp0406** [comment]
@FaeSorceress 
Thank you for your report. We have added support for the case where the adv data length is 0 in the latest version.

**Comment by Alvin1Zhang** [comment]
Thanks for contribution again, feel free to reopen.

**Pull request closed without merging**
