### PR TITLE
Some fixes on Bluetooth (IDFGH-8050)

### PR DESCRIPTION
**Pull request by tgotic**
A set of small fixes on bluetooth.
This is a new version of (IDFGH-7972) #9485 pull request, which was closed by mistake.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by Wth-Esp** [comment]
Thanks for your contribution, and I see the pre-commit check failed.

Please install `pre-commit` as [install-pre-commit](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/install-pre-commit-hook.html?highlight=pre%20commit#install-pre-commit) saying.

Thank

**Comment by tgotic** [comment]
Installed `pre-commit` and run `pre-commit install --allow-missing-config`.
Reverted commit that was failing and made new commit. Checks are failing again on a new commit.

There seems to be difference in line endings if I run `pre-commit install --allow-missing-config` from mingw environment and cmd. After running from mingw, I cannot make commit in Github desktop:
```
Mixed line ending................................................................................................................Failed
- hook id: mixed-line-ending
- exit code: 1

components/bt/host/bluedroid/bta/dm/bta_dm_pm.c: fixed mixed line endings

```
Also I ran `pre-commit run --all-files` on a fresh master branch and got massive amount of fixes. 

BTW, what is wrong with this commit?

**Comment by ruihao0** [comment]
My colleagues reviewed the code and suggested that:
```
I think these 12 commits need to be "squashed" into fewer commits, for example

1. Several commits all make changes to tBTA_DM_SEARCH_PARAM or related logics can be combined.
2. The commits to check status against HCI_SUCCESS can be squashed
3. Some small commits in changing the typos are better to be combined
```
However, in order to keep the commits count as "valid" contribution on authors profile, I can not make any change to original PR,  can you please `rebase` and `squash` your PR into a single commit? thanks.

**Comment by tgotic** [comment]
Mistake, sorry

**Pull request closed without merging**
