### PR TITLE
Add User-Agent and additional headers to esp_websocket_client (IDFGH-2193)

### PR DESCRIPTION
**Pull request by djunod**
esp_websocket_client add the ability to:
 - Change the User-Agent string.
 - Specify additional connection headers.

### CODE REVIEW

**Comment by djunod** [comment]
@igrr can I get this reviewed & merged?  Thanks

**Comment by Alvin1Zhang** [comment]
@djunod Thanks for the contribution and sorry for not replying earlier.

**Comment by djunod** [comment]
@Alvin1Zhang merge conflicts resolved.

**Comment by Alvin1Zhang** [comment]
@djunod Thanks for the contribution, merged as https://github.com/espressif/esp-idf/commit/9200250f512146e348f84ebfc76f9e82e2070da2, thank you.

**Comment by eang79** [comment]
Hi guys, 

Silly question - how do you specify additional headers for websockets? I know that is not the right place to ask but nobody seems to reply in the forum.

I tried to do it like this but it doesn't work with error shown below. I printed out the errors in the backend but there isn't an authorization key in the transaction leading to failure.

websocket_cfg.uri = CONFIG_WEBSOCKET_URI;
const char *header = "{\'authorization\': \'Token abcdefg\'}\r\n";
websocket_cfg.headers = header;
esp_websocket_client_handle_t client = esp_websocket_client_init(&websocket_cfg);
esp_websocket_register_events(client, WEBSOCKET_EVENT_ANY, websocket_event_handler, (void *)client);

I (5599) WEBSOCKET: Connecting to wss://anexample.ddns.net/...
E (23899) esp-tls: Failed to connnect to host (errno 113)
E (23899) esp-tls: Failed to open new connection
E (23899) TRANS_SSL: Failed to open a new connection
E (23899) TRANSPORT_WS: Error connecting to host mftec2149.ddns.net:443
E (23909) WEBSOCKET_CLIENT: Error transport connect

The function `esp_transport_ws_set_headers()` seems useful but its unclear how to use it. Also, specifying headers using a function in a lower-level layer seem to be correct.

Any tips or advice greatly appreciated, thanks!
Ed

**Pull request closed without merging**
