### PR TITLE
Added driver for ENC28J60 Ethernet Controller (IDFGH-2272)

### PR DESCRIPTION
**Pull request by hendog82**
I wrote a driver for the ENC28J60 Ethernet Controller.

The ENC28J60 uses SPI (similar to the DM9051) to communicate with the ESP32. The format of driver I wrote is based off of the DM9051 driver. 

I also re-wrote the "basic" ethernet example so that this driver can be used. 

I have also tested this driver with the MQTT Publish and HTTP request examples without any problems.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
@hendog82 Thanks for the contribution.

**Comment by hendog82** [comment]
How do I sign the CLA? 

When I try to sign it, it shows "You have signed the CLA for espressif/esp-idf" but when I return to this pull request it shows "Pending — Contributor License Agreement is not signed yet."

**Comment by suda-morris** [comment]
Thanks for your contribution again, could please sign the CLA again? Maybe it's caused by network issue?

**Comment by hendog82** [comment]
I couldn't sign the CLA because I was committing changes as the root user so the commits were not linked to my github. I tried to fix it but it looks like I made a whole mess.

Please use pull request #4435  instead of this one.

Thank you

**Pull request closed without merging**
