### PR TITLE
Added Bluetooth Classic HID Device support (IDFGH-1104)

### PR DESCRIPTION
**Pull request by Molorius**
Added Bluetooth Classic HID Device support along with a simple example. This is largely a port from the Google Bluedroid source.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Hi @Molorius 🙂 very nice work!
However, we are currently working on bringing HID host+device as well (and the Classic HID device is missing). I would ask you to hold a bit more on this, so we can together bring a common interface for both Host and Device on both BT and BLE. What do you say?

**Comment by Molorius** [comment]
That's great that you are planning on adding support for this, I wish I knew that before I started working on this. Do you have a timeline for when that code will be released?

**Comment by me-no-dev** [comment]
I would say we are quite close to getting it finalised and published :)
Now that I am aware of your work, I will make sure that I account this in the code and API so we can plug in your code and make it work transparent for the users wether they want to run BT, BLE or both (mix of hosts and devices as well).
On a side note, our next chip will have USB as well, so I will try to allow that to be later added as well.
Will keep you updated and I hope to have a good collaboration with you :)

**Comment by Molorius** [comment]
Please keep me updated, I would like to see this put into the main project.

**Comment by Molorius** [comment]
@me-no-dev any update on when this can be merged? Should I change it to work with the recently modified bluetooth tree?

**Comment by DerfJagged** [comment]
@me-no-dev has there been any progress on the Bluetooth HID host example? I, and quite a few others I've talked to, would absolutely love to use it on our projects!

**Comment by me-no-dev** [comment]
HID is in merge request in the internal repo. It depends on some BT controller fixes and should be merged soon :) API is prepared to be extended with BT Device, NimBle and USB for ESP32-S2

**Comment by DerfJagged** [comment]
Oh snap, you've made my day! I can't wait :)

**Comment by DerfJagged** [comment]
@me-no-dev any chance this will be in 4.3 or that we could have it posted here since it's in the internal repo? I'm itching to give it a spin!

**Comment by me-no-dev** [comment]
Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)

**Comment by chegewara** [comment]
> Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)

any update on this?

**Comment by DerfJagged** [comment]
> 
> 
> > Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)
> 
> any update on this?

Looks like it got added to master!
https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host

**Comment by chegewara** [comment]
> > > Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)
> > 
> > 
> > any update on this?
> 
> Looks like it got added to master!
> https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host

HID host != HID device

**Comment by DerfJagged** [comment]
> > > > Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)
> > > 
> > > 
> > > any update on this?
> > 
> > 
> > Looks like it got added to master!
> > https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host
> 
> HID host != HID device

https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_device

**Comment by chegewara** [comment]
> > > > > Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)
> > > > 
> > > > 
> > > > any update on this?
> > > 
> > > 
> > > Looks like it got added to master!
> > > https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host
> > 
> > 
> > HID host != HID device
> 
> https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_device

ESP-IDF BLE HID Device Demo != Bluetooth classic

**Comment by DerfJagged** [comment]
> 
> 
> > > > > > Literally waiting any day now for it to enter master (and then hopefully be backported down to 4.0)
> > > > > 
> > > > > 
> > > > > any update on this?
> > > > 
> > > > 
> > > > Looks like it got added to master!
> > > > https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host
> > > 
> > > 
> > > HID host != HID device
> > 
> > 
> > https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_device
> 
> ESP-IDF BLE HID Device Demo != Bluetooth classic

Ah, you're right. I had seen they were both added at the same time and that the HID host one covered classic. I didn't notice that the HID device one only covers BLE.

**Comment by Wth-Esp** [comment]
@Molorius 

I and my teammates are responsible for reviewing this PR, we already have a plan to merge this into IDF.
So, please wait for some time, we will contact you with some suggestions.

Thanks for your outstanding work.

Wei Tianhua

**Comment by Wth-Esp** [comment]
Hi @Molorius 

BTW.
Could you please rebase this PR on the master branch first?

Thanks

**Comment by Wth-Esp** [comment]
Hi @Molorius 

Thanks for your excellent contribution, and we finally decide to add this Classic BT HID Device module into IDF under the latest file structure. **And this will be done before 2021.1.1.**

If you have no time to continue with the code, we will rebase the code you provide. And we invite you to review the new code in another PR if you have time.

Thanks
Weitianhua

**Comment by Molorius** [comment]
Hello,

I do not have the time to rebase this right now, but I'm glad that you are working on it.

**Comment by Wth-Esp** [comment]
Hi all,

We have almost done the HID Device component based on Classic BT and we decide to have more tests on it including the BQB test case suit. I promise here the feature shall release with IDF v4.4.

Thanks for your patience, we much appreciate it.

**Comment by Molorius** [comment]
Hi,

I realize these things take time, but do you have an idea on when this feature will arrive? I am not sure how often IDF versions are incremented. 

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again, changes merged with https://github.com/espressif/esp-idf/commit/1c15c9207c0b161ef2afcb69f917ca40cf63e85e.

**Comment by Wth-Esp** [comment]
Hi, @Molorius 

We have done some changes to the original PR, if you have some suggestions please raise another issue to point it out.

Thank you very much for your excellent code again.

**Pull request closed without merging**
