### PR TITLE
example: Optimized parts of the code in the gatt_server_service_table example. (IDFGH-11491)

### PR DESCRIPTION
**Pull request by TritiumXs**
I found some redundancy in certain parts of the code, so I made modifications by removing redundant segments. These changes do not affect the functionality of the code.

### CODE REVIEW

**Comment by zhp0406** [comment]
Thank you for your feedback. The reason for writing it this way is primarily to emphasize the independence of the contents of adv_data and scan_rsp_data, aiming to prevent any potential misunderstanding on the part of the users.

**Comment by TritiumXs** [comment]
> Thank you for your feedback. The reason for writing it this way is primarily to emphasize the independence of the contents of adv_data and scan_rsp_data, aiming to prevent any potential misunderstanding on the part of the users.

Okay, but the explanation for "scan_rsp_data.p_service_data" isn't the same as for "adv_data." This is a minor detail, but if this issue can be corrected, I believe it can be improved.

**Comment by zhp0406** [comment]
Yes, we will further improve this area in the future. Do you find any other parts of the documentation unclear? We would greatly appreciate your feedback.

**Comment by TritiumXs** [comment]
> Yes, we will further improve this area in the future. Do you find any other parts of the documentation unclear? We would greatly appreciate your feedback.

Oh, indeed, there are some suggestions. UUIDs are really hard to remember. I think we can define a macro, allowing users to initialize using this macro and then modify it according to their needs. Also, the explanation for "raw_adv_data" in this example isn't very clear and may not be very friendly for developers new to BLE. I hope it can be supplemented more comprehensively.

**Comment by zhp0406** [comment]
Alright, I will explain the format of raw_scan_rsp_data in the document later to make it easier for beginners to understand.

**Comment by TritiumXs** [comment]
> Alright, I will explain the format of raw_scan_rsp_data in the document later to make it easier for beginners to understand.

And I found that the macro for "appearance" has already been defined, but it hasn't been used in the example.

**Pull request closed without merging**
