### PR TITLE
Fix offset for cosine wave function generator (IDFGH-7911)

### PR DESCRIPTION
**Pull request by floitsch**
There is no reason to treat an offset of 0 specially. On the contrary, with the special handling it's not possible to have a centered cosine wave.

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Comment by L-KAYA** [comment]
Actrually, I think we can change `-180-offset` to `offset` directly.

**Comment by floitsch** [comment]
done.

**Comment by suda-morris** [comment]
sha=5117c0a3ca2447fc03c2daebb280f5d4d78cb283

**Comment by L-KAYA** [comment]
Rebased
sha=2f307b8b654813979c13f006dd77c6b8783f36df  now

**Comment by L-KAYA** [comment]
SHA:
2f307b8b654813979c13f006dd77c6b8783f36df
3793e907909ee19864b6e99324c431b996fe37bc

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution again, feel free to reopen.

**Pull request closed without merging**
