### PR TITLE
Use /usr/bin/env bash for portability (IDFGH-708)

### PR DESCRIPTION
**Pull request by cemeyer**
bash is not always installed in /bin/bash.  This could be related to
issue #2600 (or at least, manifests with similar symptoms).

### CODE REVIEW

**Comment by cemeyer** [comment]
This change was performed mechanically, with:

```
$ find . -name \*.sh -exec sed -i "" -e 's|^#!.*bin/bash|#!/usr/bin/env bash|' {} +
```

(Note that BSD `sed -i ""` is basically identical to GNU `sed -i`.)

**Comment by cemeyer** [comment]
Thanks, @igrr !

**Comment by igrr** [comment]
@cemeyer No problem, sorry for the delay and sorry that I had to make a new commit rather than reusing the commit you have authored (it was a pain to rebase... again, due to the delay).

**Comment by cemeyer** [comment]
No worries, this is definitely the kind of thing it makes sense to just re-apply mechanically instead of trying to rebase.

**Pull request closed without merging**
