### PR TITLE
I2S-driver: Fix for ignored apll_predefine values

### PR DESCRIPTION
**Pull request by michaelwgnr**
In i2s.c, there are predefined values for audio PLL configuration in the `apll_predefine` array. In `i2s_apll_calculate`, the sampling rate supplied was compared to the bits_per_sample value in the array. This is a fix of this comparison. Furthermore, if the check had succeeded, there would have been an off-by-one error in the assignments to the output variables. This patch fixes this as well.

### CODE REVIEW

**Comment by tuanpmt** [comment]
In the next update, I think that these predefined values will not be needed any more, because the PLL calculation time is pretty fast and accurate.

**Comment by michaelwgnr** [comment]
> In the next update, I think that these predefined values will not be needed any more, because the PLL calculation time is pretty fast and accurate.

Fair enough... Will there also be fixes to PDM mode? Obviously, the clocks are calculated wrong there. (see https://esp32.com/viewtopic.php?f=13&t=3956)

**Comment by tuanpmt** [comment]
To speed up the APLL calculation, the parameters are kept fixed:
```
I2S[i2s_num]->clkm_conf.clkm_div_num = 1;
I2S[i2s_num]->clkm_conf.clkm_div_b = 0;
I2S[i2s_num]->clkm_conf.clkm_div_a = 1;
I2S[i2s_num]->sample_rate_conf.tx_bck_div_num = 8;
I2S[i2s_num]->sample_rate_conf.rx_bck_div_num = 8;
```
Meanwhile, when you use PDM mode, the parameters (clkmDecimals, clkmInteger, bck)  are dependent and is calculated in a way that does not apply to APLL

```
I2S[i2s_num]->clkm_conf.clka_en = 0;
I2S[i2s_num]->clkm_conf.clkm_div_a = 63;
I2S[i2s_num]->clkm_conf.clkm_div_b = clkmDecimals;
I2S[i2s_num]->clkm_conf.clkm_div_num = clkmInteger;
I2S[i2s_num]->sample_rate_conf.tx_bck_div_num = bck;
I2S[i2s_num]->sample_rate_conf.rx_bck_div_num = bck;
```
Apparently the i2s driver is having problems there.
I will find the appropriate way to calculate that parameters

**Comment by projectgus** [comment]
Thanks for your patience while we worked through this. As of commit 63ddae508 in the IDF master branch, the apll_predefine values are no longer used.

**Pull request closed without merging**
